const {chromium,firefox,webkit}=require('playwright');const {default:AxeBuilder}=require('@axe-core/playwright');const fs=require('fs'),assert=require('assert');
(async()=>{const checks=[],errors=[],audits=[];const b=await chromium.launch();
const test=async(name,fn)=>{try{await fn();checks.push({name,ok:true});console.log('PASS',name)}catch(e){checks.push({name,ok:false,error:e.message});console.log('FAIL',name,e.message)}};
async function framed(browser=b,sandbox=null){const c=await browser.newContext({acceptDownloads:true,viewport:{width:1440,height:1000}}),p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:3000/descargas.html');await p.evaluate(sandbox=>{document.body.innerHTML='';const f=document.createElement('iframe');f.title='Editor APA';f.style='width:100%;height:950px;border:0';if(sandbox!==null)f.setAttribute('sandbox',sandbox);f.src='http://localhost:3000/';document.body.append(f)},sandbox);const f=await(await p.locator('iframe').elementHandle()).contentFrame();await f.waitForFunction(()=>typeof readyWordRecord==='function');return {c,p,f}}
async function download(p,fn,expected){const event=p.waitForEvent('download',{timeout:10000});await fn();const d=await event;const file=await d.path();if(expected)assert.deepEqual(fs.readFileSync(file),fs.readFileSync(expected));return d}
await test('Reproducción real del error nativo Cross origin sub frames en Chromium',async()=>{const {c,f}=await framed();try{await f.evaluate(()=>{const b=document.createElement('button');b.id='nativeProbe';b.textContent='Probar API nativa';b.onclick=async()=>{try{await window.showSaveFilePicker({suggestedName:'probe.docx'});window.nativeProbeResult='UnexpectedSuccess'}catch(e){window.nativeProbeResult=e.message}};document.body.prepend(b)});await f.locator('#nativeProbe').click();await f.waitForFunction(()=>typeof window.nativeProbeResult==='string');const message=await f.evaluate(()=>window.nativeProbeResult);assert(message.includes('Cross origin sub frames'),message);fs.writeFileSync('pruebas/error-selector-reproducido.json',JSON.stringify({browser:b.version(),parent:'http://127.0.0.1:3000',child:'http://localhost:3000',actualError:message},null,2))}finally{await c.close()}});
let catalog;{const {c,f}=await framed();catalog=await f.evaluate(()=>MODEL_CATALOG.map(m=>m.id));await c.close()}
for(const id of ['base',...catalog,'guide','pack'])await test('Marco de otro origen: descarga exacta '+id+' sin selector ni documentos en base de datos',async()=>{const {c,p,f}=await framed();try{assert.equal(await f.evaluate(()=>docs.length),0);await f.evaluate(()=>{window.pickerCalls=0;window.showSaveFilePicker=async()=>{window.pickerCalls++;throw Error('No debe llamarse')}});const file=id==='base'?'Plantilla_Maestra_APA7_Word.docx':id==='guide'?'Guia_APA7_Estudio.docx':id==='pack'?'Plantillas_APA7_Word.zip':'plantillas/Plantilla_'+id.replaceAll('-','_')+'.docx';await download(p,()=>f.locator('a[data-ready-word="'+id+'"]').first().click(),file);assert.equal(await f.evaluate(()=>window.pickerCalls),0);assert(await f.locator('#saveNative').isHidden());assert(await f.locator('#downloadOutside').isVisible());assert((await f.locator('#downloadFeedback').innerText()).includes('otro origen'));if(id==='base')await p.screenshot({path:'pruebas/descarga-corregida-marco.png'})}finally{await c.close()}});
await test('Invocación residual del botón antiguo en un marco usa descarga directa, nunca picker',async()=>{const {c,p,f}=await framed();try{await f.evaluate(()=>{window.pickerCalls=0;window.showSaveFilePicker=async()=>{window.pickerCalls++;throw Error('No permitido')};showDownloadReceipt(readyWordRecord('base'))});await download(p,()=>f.evaluate(()=>savePreparedFile()),'Plantilla_Maestra_APA7_Word.docx');assert.equal(await f.evaluate(()=>window.pickerCalls),0)}finally{await c.close()}});
await test('Sandbox con allow-downloads conserva descargas nativas y evita selector',async()=>{const {c,p,f}=await framed(b,'allow-scripts allow-same-origin allow-downloads');try{await download(p,()=>f.locator('#downloadBaseHome').click(),'Plantilla_Maestra_APA7_Word.docx');assert(await f.locator('#saveNative').isHidden())}finally{await c.close()}});
await test('Sandbox sin allow-downloads no anuncia éxito y ofrece salida cuando popups están permitidos',async()=>{const {c,p,f}=await framed(b,'allow-scripts allow-same-origin allow-popups allow-popups-to-escape-sandbox');try{let downloads=0;p.on('download',()=>downloads++);await f.locator('#downloadBaseHome').click();assert(await f.locator('#saveNative').isHidden());assert(await f.locator('#downloadOutside').isVisible());const event=c.waitForEvent('page');await f.locator('#downloadOutside').click();const outside=await event;await outside.waitForFunction(()=>typeof downloadEnvironment==='function');assert.equal(await outside.evaluate(()=>self===top),true);assert.equal(await outside.evaluate(()=>downloadEnvironment().embedded),false);assert.equal(downloads,0);await download(outside,()=>outside.locator('#downloadBaseHome').click(),'Plantilla_Maestra_APA7_Word.docx')}finally{await c.close()}});
await test('Visor opaco no llama al selector ni pierde el panel de alternativas',async()=>{const {c,p,f}=await framed(b,'allow-scripts');try{await f.evaluate(()=>downloadWordTemplate());assert(await f.locator('#downloadRetry').isVisible());assert(await f.locator('#saveNative').isHidden());assert((await f.locator('#downloadFeedback').innerText()).includes('visor restringe'));assert((await f.locator('#toast').innerText()).includes('no se ha descargado'))}finally{await c.close()}});
await test('Sin API de selector: un llamado usa el archivo directo',async()=>{const c=await b.newContext({acceptDownloads:true}),p=await c.newPage();try{await p.goto('http://localhost:3000/');await p.evaluate(()=>{window.showSaveFilePicker=undefined;showDownloadReceipt(readyWordRecord('base'))});await download(p,()=>p.evaluate(()=>savePreparedFile()),'Plantilla_Maestra_APA7_Word.docx')}finally{await c.close()}});
await test('SecurityError del selector en pestaña normal activa alternativa y deshabilita nuevos intentos',async()=>{const c=await b.newContext({acceptDownloads:true}),p=await c.newPage();try{await p.goto('http://localhost:3000/');await p.evaluate(()=>{window.pickerCalls=0;window.showSaveFilePicker=async()=>{window.pickerCalls++;throw new DOMException('Blocked by policy','SecurityError')};showDownloadReceipt(readyWordRecord('base'))});await download(p,()=>p.locator('#saveNative').click(),'Plantilla_Maestra_APA7_Word.docx');assert.equal(await p.evaluate(()=>window.pickerCalls),1);assert(await p.locator('#saveNative').isHidden());assert((await p.locator('#downloadFeedback').innerText()).includes('bloqueó el selector, no el archivo'))}finally{await c.close()}});
await test('Cancelar selector no dispara otra descarga; éxito solo después de escribir y cerrar',async()=>{const c=await b.newContext(),p=await c.newPage();try{await p.goto('http://localhost:3000/');let n=0;p.on('download',()=>n++);await p.evaluate(()=>{window.showSaveFilePicker=async()=>{throw new DOMException('cancel','AbortError')};showDownloadReceipt(readyWordRecord('base'))});await p.locator('#saveNative').click();assert.equal(n,0);assert((await p.locator('#downloadFeedback').innerText()).includes('cancelado'));await p.evaluate(()=>{window.actions=[];window.showSaveFilePicker=async()=>({createWritable:async()=>({write:async blob=>{window.actions.push('write:'+blob.size)},close:async()=>{window.actions.push('close')}})})});await p.locator('#saveNative').click();assert.deepEqual(await p.evaluate(()=>window.actions),['write:'+fs.statSync('Plantilla_Maestra_APA7_Word.docx').size,'close']);assert((await p.locator('#downloadFeedback').innerText()).includes('Archivo guardado mediante'))}finally{await c.close()}});
await test('Fallo al escribir aborta el flujo y no informa éxito ni dispara descargas duplicadas',async()=>{const c=await b.newContext(),p=await c.newPage();try{await p.goto('http://localhost:3000/');await p.evaluate(()=>{window.aborted=false;window.showSaveFilePicker=async()=>({createWritable:async()=>({write:async()=>{throw Error('Disco lleno')},close:async()=>{throw Error('No debería cerrar')},abort:async()=>{window.aborted=true}})});showDownloadReceipt(readyWordRecord('base'))});await p.locator('#saveNative').click();assert(await p.evaluate(()=>window.aborted));assert((await p.locator('#downloadFeedback').innerText()).includes('No se completó la escritura'))}finally{await c.close()}});
await test('Aviso corregido accesible, responsive y explica API presente versus permiso real',async()=>{const c=await b.newContext({viewport:{width:390,height:844}}),p=await c.newPage();try{await p.goto('http://localhost:3000/');await p.evaluate(()=>{showDownloadReceipt(readyWordRecord('base'));openDownloadHelp()});const a=await new AxeBuilder({page:p}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();audits.push({name:'Ayuda de descarga corregida',violations:a.violations});assert.equal(a.violations.length,0,JSON.stringify(a.violations.map(x=>x.id)));assert((await p.locator('#dialogBody').innerText()).includes('Selector habilitado aquí'));await p.evaluate(()=>closeModal('dialogModal'));assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:'pruebas/descarga-corregida-movil.png'})}finally{await c.close()}});
for(const [name,engine] of [['Firefox',firefox],['WebKit',webkit]])await test(name+': descarga nativa en marco de otro origen',async()=>{const browser=await engine.launch();try{const {c,p,f}=await framed(browser);try{await download(p,()=>f.locator('#downloadBaseHome').click(),'Plantilla_Maestra_APA7_Word.docx');assert(await f.locator('#saveNative').isHidden())}finally{await c.close()}}finally{await browser.close()}});
await test('Sin errores JavaScript no controlados',async()=>assert.deepEqual(errors,[]));
await b.close();fs.writeFileSync('pruebas/descargas-marcos-resultados.json',JSON.stringify({checks,audits,errors},null,2));if(checks.some(x=>!x.ok))process.exitCode=1;
})();
