const {chromium}=require('playwright');const {default:AxeBuilder}=require('@axe-core/playwright');const fs=require('fs'),path=require('path'),assert=require('assert'),{pathToFileURL}=require('url');
(async()=>{const browser=await chromium.launch();const checks=[],audits=[],errors=[];fs.mkdirSync('pruebas/html-aislado',{recursive:true});const isolated=path.resolve('pruebas/html-aislado/Aplicacion_APA7.html');fs.copyFileSync('Plantilla_Maestra_APA7.html',isolated);const ctx=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost:3000/');p.on('dialog',d=>d.accept());
const test=async(name,fn)=>{try{await fn();checks.push({name,ok:true});console.log('PASS',name)}catch(e){checks.push({name,ok:false,error:e.message});console.log('FAIL',name,e.message);await p.evaluate(()=>{document.querySelectorAll('.modal.open').forEach(n=>n.classList.remove('open'));closeDownloadNotice()})}};
const download=async(q,click,file)=>{const ev=q.waitForEvent('download');await click();const dl=await ev;if(file)await dl.saveAs(file);return dl};
const audit=async(q,name)=>{const a=await new AxeBuilder({page:q}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();audits.push({name,violations:a.violations});assert.equal(a.violations.length,0,JSON.stringify(a.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))))};
// Cada archivo se prueba en una sesión aislada: no se desactivan límites de descargas del navegador.
const ids=['base',...await p.evaluate(()=>MODEL_CATALOG.map(m=>m.id)),'guide','pack'];
for(const id of ids)await test('HTML solo, offline y sin JavaScript: '+id,async()=>{const c=await browser.newContext({javaScriptEnabled:false,offline:true,acceptDownloads:true});try{const q=await c.newPage();await q.goto(pathToFileURL(isolated).href);const a=q.locator('a[data-ready-word="'+id+'"]').first();assert((await a.getAttribute('href')).startsWith('data:'));const expected=id==='base'?'Plantilla_Maestra_APA7_Word.docx':id==='guide'?'Guia_APA7_Estudio.docx':id==='pack'?'Plantillas_APA7_Word.zip':'plantillas/Plantilla_'+id.replaceAll('-','_')+'.docx';const dest='pruebas/aislado-'+path.basename(expected);const dl=await download(q,()=>a.click(),dest);assert.equal(dl.suggestedFilename(),path.basename(expected));assert.deepEqual(fs.readFileSync(dest),fs.readFileSync(expected))}finally{await c.close()}});
await test('Página independiente descargada, sola y sin JavaScript',async()=>{fs.copyFileSync('descargas.html','pruebas/html-aislado/Solo_descargas.html');const c=await browser.newContext({javaScriptEnabled:false,offline:true,acceptDownloads:true});const q=await c.newPage();await q.goto(pathToFileURL(path.resolve('pruebas/html-aislado/Solo_descargas.html')).href);const dl=await download(q,()=>q.getByRole('link',{name:'↓ Descargar plantilla normal (.docx)',exact:true}).click(),'pruebas/aislado-pagina.docx');assert.deepEqual(fs.readFileSync('pruebas/aislado-pagina.docx'),fs.readFileSync('Plantilla_Maestra_APA7_Word.docx'));await c.close()});
await test('Dashboard: datos reales, filtro, navegación y accesibilidad',async()=>{assert.equal(await p.locator('#studioDocs').innerText(),'0');assert.equal(await p.locator('#studioLessons').innerText(),'0/13');await p.locator('#homeModelSearch').fill('doctoral');assert.equal(await p.locator('.home-word-model:visible').count(),1);await p.locator('#homeModelSearch').fill('');await p.locator('#homeModelCategory').selectOption('General');assert.equal(await p.locator('.home-word-model:visible').count(),6);await p.locator('#homeModelCategory').selectOption('Todas');await audit(p,'Dashboard Studio');await p.screenshot({path:'pruebas/studio-inicio.png'})});
await test('Importar DOCX con portada, tablas, imagen, listas y niveles 1–5',async()=>{await p.locator('#wordOpenFile').setInputFiles('pruebas/trabajo-exportado.docx');await p.getByRole('button',{name:'Importar como documento nuevo',exact:true}).waitFor();await audit(p,'Confirmación de importación DOCX');await p.getByRole('button',{name:'Importar como documento nuevo',exact:true}).click();assert((await p.locator('#editor').innerText()).includes('Contenido propio con'));assert.equal(await p.locator('#editor .cover .cover-title').innerText(),'Trabajo real de prueba');assert.equal(await p.locator('#editor .cover>p').count(),6);assert(await p.locator('#editor table').count()>0);assert.equal(await p.locator('#editor .figure-wrap img').count(),1);assert((await p.locator('#editor img').getAttribute('src')).startsWith('data:image/'));for(let i=1;i<=5;i++)assert(await p.locator('#editor h'+i).count()>0);assert.equal(await p.locator('#editor h4 .runin').count(),1);assert(await p.locator('#editor ol,#editor ul').count()>0);assert((await p.locator('#editor .reference').innerText()).includes('García'));await p.screenshot({path:'pruebas/studio-editor.png'});await audit(p,'Editor con Word importado')});
await test('La portada importada conserva correctamente los campos editables',async()=>{await p.evaluate(()=>openSettings());assert.equal(await p.locator('#setAuthor').inputValue(),'María García');assert.equal(await p.locator('#setInstitution').inputValue(),'Universidad de prueba');await p.evaluate(()=>closeModal('settingsModal'))});
await test('Ribbon y modo concentración no eliminan herramientas ni contenido',async()=>{const before=await p.evaluate(()=>canonicalHTML());await p.getByRole('button',{name:'Vista',exact:true}).click();assert(await p.locator('#focusToggle').isVisible());await p.locator('#focusToggle').click();assert(!(await p.locator('.sidebar').isVisible()));await p.locator('#focusToggle').click();assert(await p.locator('.sidebar').isVisible());await p.getByRole('button',{name:'Todas',exact:true}).click();assert(await p.locator('#styleSelect').isVisible());assert.equal(await p.evaluate(()=>canonicalHTML()),before)});
await test('Buscar texto literal y reemplazar conserva negrita; deshacer restaura',async()=>{await p.evaluate(()=>{const body=editor.querySelector('.page:last-child .page-body');body.insertAdjacentHTML('beforeend','<p id="find-test" class="apa-normal">Idea a.b y <strong>a.b</strong>; aXb intacto.</p>');changed();checkpoint();openFind()});await p.locator('#findText').fill('a.b');assert((await p.locator('#findStatus').innerText()).startsWith('2 '));await p.locator('#replaceText').fill('avance');await p.getByRole('button',{name:'Reemplazar todas',exact:true}).click();assert.equal(await p.locator('#find-test strong').innerText(),'avance');assert((await p.locator('#find-test').innerText()).includes('aXb intacto'));await p.evaluate(()=>{closeModal('dialogModal');undoEdit()});assert.equal(await p.locator('#find-test strong').innerText(),'a.b')});
await test('DOCX inválido y contenido HTML hostil no dañan el trabajo',async()=>{const before=await p.evaluate(()=>canonicalHTML());await p.locator('#wordOpenFile').setInputFiles({name:'falso.docx',mimeType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',buffer:Buffer.from('<script>alert(1)</script>')});await p.waitForFunction(()=>$('toast').textContent.includes('No se pudo abrir'));assert.equal(await p.evaluate(()=>canonicalHTML()),before);const safe=await p.evaluate(()=>normaliseImportedWord('<h1 onclick="alert(1)">Título</h1><script>alert(1)</script><p>texto<img src="https://example.com/a.png" onerror="alert(1)"></p>'));assert(!safe.includes('onclick'));assert(!safe.includes('onerror'));assert(!safe.includes('https://example.com'));assert(!safe.includes('<script'))});
await test('Importar otro Word crea copia independiente',async()=>{const id=await p.evaluate(()=>currentId);await p.locator('#openFile').setInputFiles('Plantilla_Maestra_APA7_Word.docx');await p.getByRole('button',{name:'Importar como documento nuevo',exact:true}).click();assert.notEqual(await p.evaluate(()=>currentId),id);assert(await p.evaluate(id=>docs.some(d=>d.id===id),id));await p.evaluate(()=>saveState());await p.reload();await p.evaluate(()=>continueDocument());assert((await p.locator('#editor').innerText()).includes('[Título del trabajo académico]'))});
await test('Guardar con selector: escritura del Blob y cancelación sin falso éxito',async()=>{
 await p.evaluate(()=>{
  window.savedFileBytes=null;
  window.showSaveFilePicker=async()=>({createWritable:async()=>({
   write:async blob=>{window.savedFileBytes=Array.from(new Uint8Array(await blob.arrayBuffer()))},
   close:async()=>{window.fileClosed=true}
  })});
 });
 await download(p,()=>p.evaluate(()=>downloadWordTemplate()));
 await p.locator('#downloadHelpToggle').click();
 await p.locator('#saveNative').click();
 await p.waitForFunction(()=>window.fileClosed===true);
 assert.deepEqual(Buffer.from(await p.evaluate(()=>window.savedFileBytes)),fs.readFileSync('Plantilla_Maestra_APA7_Word.docx'));
 assert(await p.evaluate(()=>window.fileClosed));
 await p.evaluate(()=>{window.showSaveFilePicker=async()=>{throw new DOMException('Cancelado','AbortError')}});
 await p.locator('#saveNative').click();assert((await p.locator('#toast').innerText()).includes('cancelado'));
 await p.evaluate(()=>closeDownloadNotice());
});
await test('Trece módulos con práctica, respuestas útiles y progreso persistente',async()=>{await p.evaluate(()=>openGuide());for(let i=0;i<13;i++){await p.evaluate(i=>renderLesson(i),i);assert.equal(await p.locator('.practice-box').count(),1);const correct=await p.evaluate(i=>STUDIO_QUIZ[i].correct,i);await p.locator('.practice-options button').nth(1-correct).click();assert((await p.locator('#practiceFeedback').innerText()).includes('Inténtalo'));await p.locator('.practice-options button').nth(correct).click();assert((await p.locator('#practiceFeedback').innerText()).includes('¡Bien!'))}await audit(p,'Guía con prácticas');await p.screenshot({path:'pruebas/studio-aprender.png'});await p.evaluate(()=>{closeModal('guideModal');showHome()});assert.equal(await p.locator('#studioLessons').innerText(),'13/13');await p.reload();assert.equal(await p.locator('#studioLessons').innerText(),'13/13')});
await test('Meta personal se valida y no se presenta como requisito APA',async()=>{await p.evaluate(()=>{continueDocument();openWritingGoal()});await p.locator('#writingGoal').fill('1200');await p.getByRole('button',{name:'Guardar meta',exact:true}).click();assert.equal(await p.evaluate(()=>studioPrefs.goal),1200)});
await test('Diagnóstico de descarga y alternativas accesibles',async()=>{await p.evaluate(()=>openDownloadHelp());assert((await p.locator('#dialogBody').innerText()).includes('HTML descargado'));await audit(p,'Ayuda de descarga');await p.evaluate(()=>closeModal('dialogModal'))});
await test('Studio móvil: sin desbordamiento ni pérdida de acceso a descargas',async()=>{for(const width of [360,768,1024,1440]){await p.setViewportSize({width,height:900});await p.evaluate(()=>showHome());assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.evaluate(()=>continueDocument());assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth))}await p.setViewportSize({width:390,height:844});await p.evaluate(()=>showHome());await audit(p,'Studio móvil');await p.screenshot({path:'pruebas/studio-movil.png'})});
await test('Importación rechaza ZIP con tamaño declarado abusivo',async()=>{const raw=Buffer.from(fs.readFileSync('Plantilla_Maestra_APA7_Word.docx'));const offset=raw.indexOf(Buffer.from([0x50,0x4b,0x01,0x02]));assert(offset>=0);raw.writeUInt32LE(100*1024*1024,offset+24);const result=await pEval(raw);assert(result.includes('límite'));async function pEval(bytes){return await p.evaluate(async bytes=>{try{await APAImport.convert(Uint8Array.from(bytes).buffer);return 'aceptado'}catch(e){return e.message}},[...bytes])}});
await test('Sin errores JavaScript en Studio',async()=>assert.deepEqual(errors,[]));
fs.writeFileSync('pruebas/studio-resultados.json',JSON.stringify({checks,audits,errors,browser:browser.version()},null,2));await browser.close();if(checks.some(c=>!c.ok))process.exitCode=1;})();
