"""Catálogo único. Resúmenes didácticos propios basados en fuentes primarias consultadas."""
import json
from pathlib import Path
P=Path(__file__).parent
CHECKED='2026-09-13'
DGI='https://investigacion.upeu.edu.pe/documentos-para-el-investigador/'
def drive(id):return 'https://drive.google.com/file/d/'+id+'/view'
sources=[
 dict(id='upeu-portal',org='Universidad Peruana Unión · Dirección General de Investigación',title='Documentos para el investigador',url=DGI,date='Sin fecha de revisión visible',scope='Portal oficial de formatos, rúbricas y preliminares',status='Portal consultado',note='El portal enlaza documentos de fechas distintas. La accesibilidad del archivo no acredita que sea el formato vigente para todas las facultades.'),
 dict(id='upeu-perfil',org='UPeU · DGI',title='Plantilla perfil de proyecto de investigación',url=drive('1Hr3JI0f6zYRw83Imx_npDquVWkkU_vPt'),portal=DGI,date='2020 en la portada de la plantilla',scope='Perfil de proyecto; ajuste por diseño y unidad académica',status='Contenido primario leído',note='Usa Arial 14 en partes de la portada y remite las referencias al estilo de la revista. Esta aplicación adapta la estructura, no reproduce ese formato institucional completo.'),
 dict(id='upeu-anexo1',org='UPeU · DGI',title='Anexo 01. Elementos del perfil de proyecto/proyecto de tesis',url=drive('1bZpP8mlYOTKh7I-nAioRxg4yQpABKLdR'),portal=DGI,date='Sin fecha de revisión visible',scope='Funciones de los apartados y variantes metodológicas',status='Contenido primario leído',note='Distingue diseños cuantitativos, cualitativos, tecnológicos y documentales. No exige hipótesis o variables en todos los estudios.'),
 dict(id='upeu-fe03',org='UPeU · DGI',title='FE-03. Evaluación del trabajo de investigación/tesis en formato artículo',url=drive('1jYL7nsS_xSaUpovqgoewrgDgqwpmiITf'),portal=DGI,date='Sin fecha de revisión visible',scope='Tesis en formato artículo y manuscritos empíricos o de revisión',status='Contenido primario leído',note='La rúbrica declara que la estructura varía según la revista. Discusión, conclusiones y anexos dependen del tipo de artículo y del área. Es una rúbrica, no una plantilla editorial universal.'),
 dict(id='upeu-fe01',org='UPeU · DGI',title='FE-01. Revisión bibliográfica básica',url=drive('1I9GFzGe5D7BChvEMDqKeRJRVVhxk5Svo'),portal=DGI,date='Sin fecha de revisión visible',scope='Trabajo de revisión bibliográfica básica',status='Contenido primario leído',note='Incluye título, introducción, desarrollo, conclusiones, referencias y un informe externo de coincidencias. La herramienta no mide similitud ni plagio.'),
 dict(id='upeu-fe04',org='UPeU · DGI',title='FE-04. Evaluación del proyecto de tesis doctoral',url=drive('1AzjOKWILeaN0n7Iha3ok6ez2fEmUFsYG'),portal=DGI,date='Sin fecha de revisión visible',scope='Proyecto doctoral organizado por artículos',status='Contenido primario leído',note='Solicita división de los artículos y metodología de cada uno. No es un esquema genérico para cualquier tesis doctoral terminada.'),
 dict(id='upeu-anexo3',org='UPeU · DGI',title='Anexo 03. Informe de investigación empírica (tesis)',url=drive('0B_9dRZmkTMQbMkR0YUxHS1hmUjg'),portal='https://investigacion.upeu.edu.pe/documentos/',date='Sin fecha de revisión visible; catálogo documental anterior',scope='Tesis tradicional de cinco capítulos',status='Uso condicionado: confirmar con el programa',note='El documento indica A4 y preliminares institucionales. No se ofrece como equivalente a un Word oficial vigente; la adaptación usa Carta y APA 7.'),
 dict(id='upeu-descartada',org='UPeU · DGI',title='Archivo enlazado como plantilla tradicional cuantitativa',url=drive('1NuBRKqmvs5zdHpLLDBzAjRdA_alcy-hY'),portal='https://investigacion.upeu.edu.pe/documentos/',date='Archivo con referencia explícita a APA 6',scope='Archivo contrastado y no seleccionado como base',status='Descartado como modelo principal',note='Aunque el enlace menciona tesis tradicional, el archivo contiene un proyecto con diez capítulos, cronograma y presupuesto. Se detectó referencia a APA sexta edición; no se trasladaron sus instrucciones como APA 7.'),
 dict(id='uc-texto',org='Pontificia Universidad Católica de Chile · Comunicación Académica',title='Cómo estructurar un texto académico',url='https://comunicacionacademica.uc.cl/images/recursos/espanol/escritura/recurso_en_pdf_extenso/13_Como_estructurar_un_texto_academico.pdf',date='Sin fecha de publicación visible',scope='Guía didáctica de introducción, desarrollo y conclusión',status='Contenido primario leído',note='Explica propósitos argumentativos, expositivos y explicativos. No constituye un reglamento de tesis ni fija un esquema para todas las carreras.'),
 dict(id='uchile-informe',org='Universidad de Chile · Aprendizaje',title='¿Cómo escribir un informe?',url='https://aprendizaje.uchile.cl/recursos-para-leer-escribir-y-hablar-en-la-universidad/profundundiza/profundiza-la-escritura/como-escribir-un-informe/'.replace('profundundiza','profundiza'),date='Sin fecha de revisión visible',scope='Informes académicos; variantes según disciplina',status='Contenido primario leído',note='El recurso distingue informes de laboratorio, práctica, investigación y bibliográficos. Los apartados concretos dependen del género y de la consigna docente.'),
 dict(id='upn-monografia',org='Universidad Privada del Norte · Estudios Generales',title='Aprende a hacer una monografía paso a paso con esta guía definitiva',url='https://blogs.upn.edu.pe/estudios-generales/que-es-monografia',date='12 de abril de 2024 en la página consultada',scope='Orientación divulgativa universitaria para monografías',status='Contenido primario leído',note='Identifica carátula, índice, cuerpo, conclusión, bibliografía y anexos; no todos son obligatorios en todos los encargos. No es reglamento institucional de titulación.'),
 dict(id='pucp-educacion',org='PUCP · Revista Educación',title='Normas para autores',url='https://revistas.pucp.edu.pe/index.php/educacion/normas_autores',date='Sin fecha de revisión visible',scope='Envíos a esta revista, no a todas las universidades',status='Contenido primario leído',note='Pide Word, A4, Arial 11, interlineado 1,5 y manuscrito anónimo; título/resumen en tres idiomas. Contrasta con la base APA de esta app. No se automatiza un envío listo para esta revista.'),
]
for s in sources:s['checked']=CHECKED

def section(key,name,guide,level=1,optional=False,example='',check='',kind='text'):
 return dict(key=key,name=name,level=level,optional=optional,guide=guide,example=example or 'Redacta con tus datos, tu contexto y fuentes comprobables; no copies un ejemplo como si fuera un resultado real.',check=check or '¿Este apartado cumple su función y se relaciona con el objetivo del trabajo?',kind=kind)
def S(k,n,g,**kw):return section(k,n,g,**kw)
R=S('referencias','Referencias','Incluye solo fuentes utilizadas y citadas. Comprueba autor, fecha, título y procedencia; ordénalas alfabéticamente con sangría francesa.',check='¿Cada cita tiene su referencia y cada referencia está citada?')
A=S('anexos','Anexos','Agrega materiales complementarios citados en el cuerpo. No incluyas datos identificables, consentimientos firmados ni permisos que no poseas.',optional=True,check='¿Cada anexo aporta evidencia necesaria y protege la confidencialidad?')
intro=S('introduccion','Introducción','Contextualiza el tema, delimita el problema, explica el propósito y anticipa la organización del texto.',example='Este trabajo analiza [tema] en [contexto] para [propósito]. Se organiza en [apartados].',check='¿El lector comprende qué estudiarás, para qué y con qué alcance?')
con=S('conclusiones','Conclusiones','Responde al propósito a partir de lo que desarrollaste. Distingue lo demostrado de lo que no puede concluirse; no introduzcas datos nuevos.',check='¿Las conclusiones están respaldadas por el desarrollo y no exageran los hallazgos?')
res=S('resumen','Resumen','Resume propósito, método, hallazgos reales y conclusión. Redáctalo al final y respeta la extensión del destino; no adelantes resultados que no existen.',check='¿Resume fielmente el trabajo y respeta el límite confirmado?',kind='noindent')
kw=S('palabras-clave','Palabras clave','Elige términos precisos de búsqueda. FE-03 orienta a 3–5; confirma el número exigido por la revista.',level=2,kind='keywords')
abstract=S('abstract','Abstract','Traduce fielmente el resumen al inglés y revisa la terminología. No agregues ni cambies resultados.',kind='noindent')
keywords=S('keywords','Keywords','Usa los equivalentes en inglés de las palabras clave.',level=2,kind='keywords')
method=S('metodo','Metodología','Describe diseño, participantes o fuentes, instrumentos, procedimiento, análisis y resguardo ético. En un informe final narra lo efectivamente realizado.',check='¿Otra persona podría comprender y examinar el procedimiento?')
results=S('resultados','Resultados','Organiza los hallazgos reales en el orden de los objetivos. Usa tablas o figuras pertinentes sin repetir todos los datos en el texto.',check='¿Los resultados se apoyan en los datos y no se confunden con interpretación?')
disc=S('discusion','Discusión','Interpreta los resultados frente al objetivo y a estudios previos. Explica coincidencias, diferencias, limitaciones e implicaciones sin sobregeneralizar.',check='¿Contrastas con fuentes pertinentes y reconoces las limitaciones?')
ethics=S('etica','Aspectos éticos','Explica evaluación ética, consentimiento, permisos, privacidad y conflictos aplicables. Confirma la normativa vigente con el comité: no supongas exención ni fabriques aprobaciones.',level=2,check='¿Tienes las aprobaciones o la determinación de exención que correspondan antes de recolectar datos?')
chrono=S('cronograma','Cronograma de actividades','Planifica actividades, responsables y fechas coherentes; incluye revisión, permisos, recolección, análisis, redacción y cierre. Usa una tabla o Gantt.',level=2,kind='schedule',check='¿Las actividades caben en el plazo y respetan las dependencias?')
budget=S('presupuesto','Presupuesto proyectado','Detalla recursos, cantidades, costos unitarios, totales y financiación. Sustenta los valores; no presentes precios inventados como cotizaciones.',level=2,kind='budget',check='¿Los cálculos y las fuentes de financiación son verificables?')
baseChecklist=['Confirmé la consigna, el tipo de trabajo y el reglamento o guía que me corresponde.','Verifiqué si la portada y los preliminares institucionales requieren archivos oficiales.','Mis afirmaciones, datos y citas tienen fuentes o evidencia; no inventé resultados.','Revisé referencias, ortografía, contenido y el archivo Word final.']
models=[]
def model(id,label,category,org,src,sections,summary,why,**kw):
 d=dict(id=id,label=label,category=category,org=org,sources=src,sections=sections,summary=summary,why=why,checked=CHECKED,revision='1',cover=True,toc=False,status='Adaptación educativa',scope='Estructura guiada; formato base APA 7',warnings=[],checklist=baseChecklist.copy(),institutional=False,historical=False,adaptation='Las explicaciones son una paráfrasis didáctica propia. La selección y rotulación de apartados se adapta a esta herramienta; no es una reproducción ni aprobación institucional.')
 d.update(kw);models.append(d);return d
model('academico','Trabajo académico','General','Guía UC Chile',['uc-texto'],[intro,S('desarrollo','Desarrollo','Expón y relaciona las ideas según el propósito: argumentar, explicar o describir. Divide en subtemas que aporten a ese propósito.'),con,R],'Una base flexible para tareas universitarias.','Se eligió una guía universitaria que explica la función de cada parte, sin imponer una estructura de tesis.',warnings=['No existe un formato universal de trabajo académico. Sigue primero la consigna del docente.'])
model('ensayo','Ensayo','General','Guía UC Chile',['uc-texto'],[S('introduccion','Introducción','Presenta el problema debatible y formula tu tesis o postura. Explica su relevancia y anticipa la línea argumentativa.',example='Sostengo que [postura delimitada] porque [razones que desarrollarás].'),S('argumentacion','Argumentación','Desarrolla una razón por párrafo, aporta evidencia y explica cómo sostiene tu tesis. Considera objeciones y respóndelas con argumentos.',example='Una objeción a [tesis] es [objeción]. Sin embargo, [evidencia y razonamiento].',check='¿Hay una tesis defendida con evidencia, no solo opiniones o resúmenes?'),con,R],'Defiende una postura con razones y fuentes.','La guía UC distingue explícitamente la organización argumentativa; no se confundió un ensayo de curso con un manuscrito de revista.',warnings=['Los rótulos Introducción, Argumentación y Conclusiones pueden omitirse si tu docente pide un texto continuo. No es una tesis de grado.'])
model('informe','Informe','General','Guía Universidad de Chile',['uchile-informe'],[intro,S('objetivos','Objetivos','Indica lo que se pretende reportar o evaluar y delimita el alcance.'),S('procedimiento','Procedimiento','Explica materiales, método y actividades relevantes según el tipo de informe. Para un informe bibliográfico, describe cómo elegiste y analizaste las fuentes.'),results,con,R],'Informa sobre una actividad, análisis o experiencia.','Se eligió una guía que reconoce variantes por disciplina en lugar de imponer el formato de laboratorio a cualquier informe.',warnings=['Objetivos, procedimiento y resultados son una variante didáctica. Un informe bibliográfico o de práctica puede usar otros títulos.'])
model('monografia','Monografía','General','Orientación UPN',['upn-monografia','uc-texto'],[intro,S('marco','Marco teórico','Delimita conceptos y perspectivas necesarios para comprender el tema, sustentándolos con fuentes.'),S('desarrollo','Desarrollo','Organiza el análisis del tema delimitado por subtemas. Compara y sintetiza fuentes; no acumules fragmentos copiados.'),con,R,A],'Profundiza en un tema delimitado mediante fuentes.','La guía UPN identifica los componentes del género; se añade introducción y división del cuerpo como ayuda didáctica, no como mandato UPN.',toc=True,warnings=['En la fuente se usa el término Bibliografía; la adaptación emplea Referencias para las fuentes citadas según APA. El marco teórico separado no es universal.'])
profile=[S('planteamiento','1. Planteamiento del problema','Sitúa el problema y delimita qué vacío o necesidad atenderás. Este bloque agrupa justificación, antecedentes recientes, objetivos y supuestos pertinentes.'),S('justificacion','1.1 Justificación','Explica por qué y para qué estudiarás el tema, a quién beneficia y cuál es la utilidad. Fundamenta la necesidad con evidencia.',level=2),S('estado-arte','1.2 Estado del arte','Sintetiza críticamente investigaciones y controversias pertinentes. Termina con el vacío que tu estudio busca abordar, no con una lista de resúmenes.',level=2),S('objetivos','1.3 Objetivos','Formula un objetivo general con un verbo en infinitivo y, cuando corresponda, objetivos específicos que contribuyan a él.',level=2,example='Determinar [relación/característica] en [población o unidades] de [contexto y periodo].'),S('hipotesis','1.4 Hipótesis','Formula respuestas contrastables solo si el diseño las requiere y vincúlalas con los objetivos. No todos los estudios tienen hipótesis.',level=2,optional=True),S('variables','1.5 Variables','Define las variables que correspondan. En estudios cualitativos o documentales usa categorías u otra organización pertinente; no impongas variables.',level=2,optional=True),S('metodologia','2. Metodología','Describe lo que se hará, con suficiente detalle para valorar coherencia y factibilidad.'),S('diseno','2.1 Diseño metodológico','Justifica enfoque y diseño a partir de la pregunta, no solo con etiquetas o definiciones generales.',level=2),S('muestra','2.2 Diseño muestral','Define población o corpus, unidad de análisis, selección, tamaño y criterios pertinentes. Puede tratarse de documentos, no necesariamente personas.',level=2),S('recoleccion','2.3 Técnicas de recolección de datos','Explica técnicas, instrumentos, procedimientos y evidencia de validez/confiabilidad cuando proceda.',level=2),S('analisis','2.4 Procesamiento de la información','Describe el análisis planificado y su justificación. Incluye software y procedimientos; si no es estadístico, explica el análisis cualitativo o documental.',level=2),dict(ethics,name='2.5 Aspectos éticos'),S('administracion','3. Administración del proyecto','Comprueba que tiempo, recursos, permisos y financiación permiten ejecutar la propuesta.'),dict(chrono,name='3.1 Cronograma de actividades'),dict(budget,name='3.2 Presupuesto proyectado'),dict(R,name='4. Referencias bibliográficas'),S('anexo-a','5. Anexo A. Instrumentos','Incluye instrumentos en blanco y el modelo de consentimiento cuando aplique; no anexes datos personales reales.',optional=True),S('anexo-b','6. Anexo B. Operacionalización','Presenta la matriz cuando existan variables que deban operacionalizarse.',optional=True),S('anexo-c','7. Anexo C. Material complementario','Incluye imágenes, planos, figuras o tablas pertinentes y citados en el proyecto.',optional=True)]
m=model('upeu-perfil','Proyecto','UPeU','UPeU · perfil de proyecto',['upeu-perfil','upeu-anexo1'],profile,'Planifica una investigación antes de ejecutarla.','Se eligió la plantilla de perfil enlazada por el portal DGI y se contrastó con el Anexo 01; no se usó el archivo ambiguo rotulado como tesis tradicional.',institutional=True,toc=True,status='Fuente enlazada por DGI · confirmar vigencia',scope='Perfil de proyecto de investigación; fuente con portada 2020',warnings=['La plantilla fuente muestra 2020. Consulta si tu facultad utiliza una versión posterior.','La fuente pide Arial 14 en partes de portada y referencias según la revista. Aquí se conserva APA 7, Carta y TNR 12; no es el formulario oficial listo para trámite.','Las longitudes orientativas del archivo fuente no son reglas APA. Hipótesis, variables y anexos dependen del diseño.']);m['checklist']+=['Confirmé la versión de perfil con mi asesor y no confundí un proyecto con una tesis final.','Definí cómo tramitaré las aprobaciones y permisos antes de recolectar información.','Verifiqué cronograma, presupuesto y financiación.']
article=[res,kw,abstract,keywords,intro,method,results,dict(disc,optional=True),dict(con,optional=True),R,A]
m=model('upeu-tesis-articulo','Tesis en formato artículo','UPeU','UPeU · FE-03',['upeu-fe03','upeu-portal'],article,'Presenta una investigación de grado con organización de artículo.','FE-03 corresponde explícitamente a tesis en formato artículo y reconoce variaciones por revista; se prioriza frente a modelos antiguos de diez capítulos.',institutional=True,status='Rúbrica oficial consultada',warnings=['FE-03 no fija una revista ni sustituye su guía de autores. Confirma el destino, el tipo de estudio y los preliminares exigidos por tu programa.','Las plantillas oficiales de portada, declaración y evaluación se consultan en el portal DGI. No se fabrican sellos, firmas, actas ni aprobaciones.','Discusión y conclusiones pueden ser independientes o integradas según la revista.']);m['checklist']+=['Confirmé que mi programa admite tesis en formato artículo y la revista de referencia.','Tengo los preliminares oficiales y documentos de aprobación requeridos.','Separé resultados reales, interpretación y conclusiones.']
model('upeu-articulo','Artículo de investigación','UPeU','UPeU · FE-03',['upeu-fe03'],article,'Comunica resultados empíricos como manuscrito.','Se usa la rúbrica primaria de UPeU como guía general; la revista elegida mantiene la prioridad editorial.',cover=False,institutional=True,status='Rúbrica oficial consultada',warnings=['No es una plantilla de envío a cualquier revista. Extensión, anonimato, idiomas, autores y estilo final deben ajustarse al destino.','Título y autoría se colocan en un bloque inicial, no en una portada estudiantil separada por defecto.'])
model('upeu-revision','Revisión bibliográfica básica','UPeU','UPeU · FE-01',['upeu-fe01'],[intro,S('desarrollo','Desarrollo','Organiza el tema mediante comparaciones y discusiones de las fuentes. Cada argumento necesita evidencia y una explicación propia.'),con,R],'Analiza y articula literatura sin afirmar una revisión sistemática.','Se conserva la estructura breve indicada en FE-01, sin añadir métodos de revisión sistemática que la fuente no exige.',institutional=True,titleMax=15,status='Rúbrica oficial consultada',warnings=['FE-01 indica un título de hasta 15 palabras y exige un informe externo de coincidencias. Confirma la versión y el procedimiento institucional.','Esta aplicación no calcula porcentaje de similitud ni certifica ausencia de plagio.'])
model('upeu-revision-articulo','Artículo de revisión','UPeU','UPeU · FE-03',['upeu-fe03'],[res,kw,abstract,keywords,intro,S('metodo','Metodología de la revisión','Explica fuentes o bases, términos, fechas, idiomas, criterios de selección y forma de síntesis. No llames sistemática a una revisión que no siguió un protocolo reproducible.'),S('sintesis','Desarrollo y síntesis','Sintetiza los estudios seleccionados por ejes temáticos y evalúa acuerdos, discrepancias y limitaciones. Mantén trazabilidad entre afirmaciones y fuentes.'),dict(disc,optional=True),dict(con,optional=True),R,A],'Explica una búsqueda y sintetiza críticamente sus resultados.','FE-03 aporta instrucciones específicas para delimitar la búsqueda de artículos de revisión.',cover=False,institutional=True,status='Rúbrica oficial consultada',warnings=['Las revisiones sistemáticas requieren además la guía de reporte y el protocolo que correspondan; esta plantilla no certifica PRISMA ni incorpora automáticamente sus 27 ítems.'])
doctoral=[S('planteamiento','Planteamiento del problema','Delimita una contribución doctoral coherente que articule todos los artículos.'),S('justificacion','Justificación','Argumenta la relevancia científica y la aportación que excede la suma de artículos aislados.',level=2),S('objetivos','Objetivos','Expresa el objetivo integrador y los objetivos de cada artículo.',level=2),S('hipotesis','Hipótesis','Formula supuestos contrastables cuando el diseño lo requiera.',level=2,optional=True),S('variables','Variables','Define variables o categorías pertinentes a cada artículo y su relación con el conjunto.',level=2,optional=True),S('division','División de los artículos','Describe el tema, pregunta y contribución de cada artículo. No presupongas un número universal: confírmalo con el programa.'),S('metodologia','Metodología de cada artículo','Detalla diseño, muestras o fuentes, técnicas, instrumentos, análisis y ética para cada artículo; puedes duplicar subsecciones.'),dict(ethics,level=2),S('administracion','Administración del proyecto','Articula tiempos y recursos del proyecto doctoral completo.'),chrono,budget,R,A]
m=model('upeu-doctoral','Proyecto de tesis doctoral','UPeU','UPeU · FE-04',['upeu-fe04'],doctoral,'Diseña un proyecto doctoral articulado por artículos.','Se eligió la rúbrica específica FE-04, no un proyecto de pregrado ampliado.',institutional=True,toc=True,titleMax=15,status='Rúbrica oficial consultada',warnings=['FE-04 pide título tentativo de hasta 15 palabras, división y metodología por artículo e informe externo de coincidencias. Confirma su vigencia con la unidad de posgrado.','Es un proyecto doctoral, no el informe final de una tesis doctoral.']);m['checklist']+=['Definí la contribución integrada y el método de cada artículo con mi asesor.','Confirmé el número y condiciones de los artículos y los requisitos externos del programa.']
trad=[S('dedicatoria','Dedicatoria','Inclúyela solo si deseas y el programa la admite.',optional=True),S('agradecimientos','Agradecimientos','Reconoce contribuciones y apoyos pertinentes. Omite si no corresponde.',optional=True),dict(res,guide='Resume objetivo, método, resultados reales y conclusión. El Anexo 03 consultado indica hasta 300 palabras; confirma si tu programa mantiene ese límite.'),dict(kw,guide='Selecciona 5–6 términos clave según el Anexo 03 consultado; confirma el criterio vigente del programa.'),abstract,keywords,S('cap1','Capítulo I. El problema','Presenta identificación del problema, justificación, presuposición filosófica si corresponde y objetivos.'),S('identificacion','Identificación del problema','Delimita el problema y apoya el contexto con evidencia.',level=2),S('justificacion','Justificación','Explica la utilidad y pertinencia del estudio.',level=2),S('filosofia','Presuposición filosófica','Desarrolla la fundamentación filosófica cuando la unidad académica la requiera.',level=2,optional=True),S('objetivos','Objetivos','Expresa el propósito y los objetivos coherentes con el enfoque.',level=2),S('cap2','Capítulo II. Revisión de la literatura / Marco teórico','Analiza antecedentes, fundamentos teóricos y métodos relevantes; contrasta evidencia, no solo definiciones.'),S('cap3','Capítulo III. Materiales y métodos','Explica cómo se ejecutó realmente la investigación, incluidos ajustes respecto del proyecto, procedimientos, análisis y ética.'),S('cap4','Capítulo IV. Resultados y discusión','Presenta hallazgos y contrástalos con la literatura en el orden de los objetivos; reconoce limitaciones.'),S('cap5','Capítulo V. Conclusiones y recomendaciones','Expone aprendizajes y aportes sustentados. Distingue conclusiones de propuestas para futuras investigaciones.'),R,A]
model('upeu-tradicional','Tesis tradicional','UPeU','UPeU · Anexo 03',['upeu-anexo3'],trad,'Modelo de cinco capítulos, sujeto a confirmación del programa.','Se seleccionó el Anexo 03 cuyo contenido sí describe un informe final; se descartó el archivo que mezcla título de tesis con proyecto y APA 6.',institutional=True,historical=True,toc=True,status='Uso condicionado · confirmar versión',scope='Anexo de catálogo anterior; no confirmado como requisito vigente',warnings=['No se recomienda asumir este modelo para un trámite nuevo sin autorización del programa.','La fuente indica A4, hasta 300 palabras de resumen, 5–6 palabras clave y preliminares específicos. La adaptación conserva Carta y formato APA 7.','Ficha catalográfica, hoja de evaluación, declaración, índices de tablas/figuras y códigos CRAI no se generan como si fueran documentos oficiales.']);
# Conserva la estructura didáctica de Enfermería del proyecto original.
nursing=[intro,S('definicion','Definición','Delimita la condición o tema mediante fuentes académicas actuales.'),S('fisiopatologia','Fisiopatología','Explica mecanismos relevantes conectando procesos normales y alteraciones; sustenta las afirmaciones.'),S('manifestaciones','Manifestaciones clínicas','Organiza signos, síntomas y hallazgos según fuentes clínicas; no diagnostiques a una persona desde este texto.'),S('tratamiento','Tratamiento','Describe el abordaje respaldado por guías y distingue decisiones profesionales de información académica.'),S('farmacologia','Farmacología','Explica grupos y mecanismos pertinentes usando fuentes verificadas; no inventes dosis ni conviertas el trabajo en una prescripción.'),S('cuidados','Cuidados de Enfermería','Relaciona valoración, prioridades, objetivos de cuidado, intervenciones fundamentadas y evaluación según la consigna.'),con,R]
model('enfermeria','Trabajo de Enfermería','General','Modelo didáctico propio',[],nursing,'Organiza una revisión académica de un tema de salud.','Se conserva la estructura útil del proyecto; se etiqueta como didáctica propia porque no se verificó un formato institucional específico para ella.',warnings=['No es una plantilla oficial de UPeU ni un plan de cuidados universal. Verifica la guía del curso y los protocolos clínicos pertinentes.','No incorpora datos reales de pacientes ni reemplaza juicio clínico.'])
# Contraste editorial específico: nunca lo hacemos pasar por formato APA institucional idéntico.
model('ensayo-editorial','Ensayo para revista Educación','Revista','PUCP · Educación',['pucp-educacion'],[res,S('resumos','Resúmenes en inglés y portugués','Prepara traducciones equivalentes al resumen y términos clave en los tres idiomas. La página consultada pide resumen de hasta 130 palabras y 3–5 términos científicos.'),intro,S('desarrollo','Desarrollo','Argumenta críticamente un problema educativo, fundamentando la postura con fuentes.'),con,R],'Adaptación estructural de un ensayo para una revista concreta.','Permite enseñar que los requisitos editoriales pueden diferir del formato APA de la aplicación.',cover=False,institutional=True,status='Normas editoriales consultadas',warnings=['La revista exige A4, Arial 11, interlineado 1,5 y manuscrito anónimo. Este Word mantiene APA base y NO está listo para envío sin ajustar el formato y eliminar identificadores.','La página indica 5000–7000 palabras para ensayos y una hoja de autores separada. Verifica nuevamente las normas antes de enviar.'])
model('otro','Otro / documento libre','General','Personalizado',[],[intro,S('desarrollo','Desarrollo','Organiza el contenido según tu consigna y añade o elimina apartados.'),con,R],'Comienza con una estructura editable sin atribución institucional.','Permite adaptar consignas que no estén cubiertas por fuentes verificadas.',warnings=['No se ha asociado una guía institucional. Registra tus requisitos en Configuración.'])
examples_by_key={
 'introduccion':'Este trabajo aborda [tema delimitado] en [contexto]. Su propósito es [objetivo] y se organiza en [partes].',
 'justificacion':'La investigación es pertinente porque [necesidad respaldada por evidencia]. Sus aportes permitirían [utilidad concreta] para [destinatarios].',
 'estado-arte':'[Fuente A] estudió [aspecto]; [fuente B] encontró [hallazgo]. Sus alcances difieren en [criterio]. Persiste un vacío sobre [problema].',
 'objetivos':'Analizar [objeto de estudio] en [población o corpus], considerando [alcance, contexto y periodo].',
 'hipotesis':'En [contexto], se espera que [relación contrastable entre variables]. La hipótesis se evaluará mediante [procedimiento coherente].',
 'variables':'Variable: [nombre]. Definición conceptual: [definición con fuente]. Definición operacional: [cómo se observará o medirá].',
 'diseno':'Se propone un estudio [diseño] porque permite responder [pregunta] mediante [tipo de evidencia].',
 'muestra':'La población o corpus comprende [unidades]. Se seleccionará [muestra] mediante [procedimiento y justificación], con criterios de [inclusión/exclusión].',
 'recoleccion':'Se empleará [instrumento o técnica] para obtener [información]. Se documentará [validez, confiabilidad u otro criterio pertinente].',
 'analisis':'La información se analizará mediante [procedimiento], seleccionado por [razón vinculada a las preguntas y los datos].',
 'etica':'Antes de recolectar datos se gestionará [evaluación o permiso aplicable]. La información se protegerá mediante [medidas específicas]. No afirmes que se aprobó si aún está pendiente.',
 'cronograma':'Actividad: [trámite ético]. Inicio: [fecha]. Fin: [fecha]. Dependencia: [aprobación previa a la recolección, cuando corresponda].',
 'presupuesto':'Recurso: [nombre]. Cantidad: [n]. Costo unitario: [importe sustentado]. Total: [cantidad × costo]. Financiación: [fuente].',
 'resultados':'Respecto del objetivo [n], se encontró [resultado real]. La Tabla [n] presenta [datos necesarios para examinarlo].',
 'discusion':'El hallazgo [resultado real] coincide o contrasta con [estudio citado]. Una explicación posible es [argumento sustentado], aunque [limitación].',
 'conclusiones':'En relación con [objetivo], la evidencia permite concluir [conclusión delimitada]. No permite establecer [alcance que excedería los datos].',
 'resumen':'Objetivo: [propósito]. Método: [procedimiento realmente utilizado]. Resultados: [hallazgos]. Conclusión: [respuesta al objetivo]. Redáctalo como un párrafo si así lo exige el destino.',
 'palabras-clave':'[término preciso 1], [término preciso 2], [término preciso 3]. No uses estos marcadores como términos finales.',
 'referencias':'Autor, A. A. (Año). Título de la obra. Editorial. Es solo una estructura para un libro: completa una fuente real y utiliza el modelo correspondiente a su tipo.',
 'division':'Artículo [n]: [pregunta y propósito]. Aporte al objetivo doctoral: [conexión]. Método previsto: [resumen].',
}
for m in models:
 for section in m['sections']:
  if section['key'] in examples_by_key and section['example'].startswith('Redacta con tus datos'):
   section['example']=examples_by_key[section['key']]
for m in models:
 for s in m['sections']:
  assert 1<=s['level']<=5
  assert s['guide'] and s['check'] and s['example']
 assert len({s['key'] for s in m['sections']})==len(m['sections']),m['id']
catalog=dict(revision='2026-09-13.1',checked=CHECKED,policy='Una adaptación estructural no equivale a una plantilla oficial. Confirma siempre programa, modalidad y versión. El formato base permanece APA 7.',sources=sources,models=models)
(P/'catalogo.json').write_text(json.dumps(catalog,ensure_ascii=False,indent=2))
print(len(models),'modelos;',len(sources),'fuentes trazables')
