from pathlib import Path
import json
ROOT=Path(__file__).resolve().parent.parent
cat=json.loads((ROOT/'proyecto/catalogo.json').read_text())
lines=['# Fuentes y modelos guiados — Plantilla Maestra APA 7','',f'Consulta documentada: **{cat["checked"]}** · Revisión de la adaptación: **{cat["revision"]}**.','', '## Criterio de selección','', 'Se priorizaron documentos primarios enlazados por la Dirección General de Investigación de UPeU. Se leyó el contenido de las plantillas y rúbricas, no solo el título del enlace. Para géneros no cubiertos por un formato UPeU específico verificado, se recurrió a guías universitarias pertinentes. No se utilizó un ejemplo de tesis de repositorio como si fuese una norma general.','', 'Se compararon finalidad, estructura, fecha visible, ámbito y diferencias de formato. Las instrucciones de llenado, preguntas y ejemplos son una elaboración didáctica propia basada en esas funciones; no son citas textuales ni una aprobación institucional.','', '### Hallazgos y límites importantes','', '- La plantilla de perfil UPeU conserva 2020 en su portada. Las rúbricas FE consultadas no muestran una fecha de revisión verificable. Estar enlazadas en el portal no acredita vigencia para todos los programas.', '- El archivo enlazado como plantilla tradicional cuantitativa contiene en realidad un proyecto de diez capítulos y menciona APA 6. Se descartó como modelo principal de tesis APA 7.', '- El Anexo 03 sí desarrolla un informe final de cinco capítulos, pero procede de una colección documental anterior e indica A4. Se incluye solo como opción condicionada a la confirmación del programa.', '- La consulta del reglamento 2025 mediante el lector Issuu no permitió verificar su contenido. No se atribuyen a ese reglamento requisitos no leídos.', '- Los archivos institucionales de preliminares enlazados desde el portal no se verificaron íntegramente ni se reproducen como oficiales. No se generaron actas, firmas o documentos de aprobación.', '- La ruta antigua “documentos-procesos-iniciados-hasta-2019” devolvió página no encontrada. Se utiliza la colección accesible `/documentos/`, no esa ruta rota.', '- Las reglas de la revista Educación no coinciden con el formato base de la aplicación. Su modelo es una adaptación estructural, no un archivo listo para enviar.', '- No se trasladan porcentajes de similitud, cantidades de referencias ni criterios particulares de rúbricas como reglas universales APA. Esta app no calcula plagio ni certifica originalidad.','', '## Fuentes consultadas','']
for i,s in enumerate(cat['sources'],1):
 lines += [f'### {i}. {s["title"]}',f'- Institución: {s["org"]}.',f'- Estado: {s["status"]}.',f'- Fecha visible: {s["date"]}.',f'- Alcance: {s["scope"]}.',f'- Fuente primaria: [{i}]({s["url"]}).',f'- Observación: {s["note"]}.','']
lines+=['## Catálogo y guía de llenado','','En Word, sustituye los corchetes y retira la ficha didáctica. En la web, la guía permanece fuera de la hoja por defecto. Los modelos que incluyen índice lo generan como campo actualizable; el índice no es una exigencia universal APA.','']
for m in cat['models']:
 lines += [f'## {m["label"]}',m['summary'],'',f'**Procedencia:** {m["org"]}. **Estado:** {m["status"]}.',f'**Word preparado:** `plantillas/Plantilla_{m["id"].replace("-","_")}.docx`.',f'**Por qué se eligió:** {m["why"]}.',m['adaptation'],'','### Precauciones']
 lines += ['- '+w for w in m['warnings']]
 lines += ['', '### Apartados']
 for sec in m['sections']:
  kind='etiqueta de términos, no encabezado' if sec['kind']=='keywords' else 'nivel '+str(sec['level'])
  lines += ['',f'#### {sec["name"]} · {kind}'+(' · si corresponde' if sec['optional'] else ''),sec['guide'],f'**Pregunta de control:** {sec["check"]}',f'**Ejemplo orientativo; no son datos reales:** {sec["example"]}']
 lines+=['','### Autoevaluación']+['- [ ] '+x for x in m['checklist']]+['','**Fuentes de este modelo:** '+(', '.join(f'[{next(i for i,s in enumerate(cat["sources"],1) if s["id"]==sid)}]({next(s["url"] for s in cat["sources"] if s["id"]==sid)})' for sid in m['sources']) or 'Modelo didáctico propio; sin atribución institucional.') ,'']
(ROOT/'FUENTES_Y_MODELOS_APA7.md').write_text('\n'.join(lines))
print('Guía y trazabilidad documentadas')
