/* APA Styles, Structure, Tutor y selección. Se conservan las acciones de v2. */
const stylesAPA={
 'apa-normal':['Texto normal — Párrafo APA','Cuerpo principal del trabajo.','Times New Roman 12 · doble · primera línea 1,27 cm','p'],
 'apa-noindent':['Texto sin sangría','Bloques que necesitan comenzar en el margen izquierdo. No sustituye el párrafo de cuerpo.','Times New Roman 12 · doble · sin sangría','p'],
 'blockquote':['Cita larga','Citas textuales de 40 palabras o más, sin comillas. Añade autor, año y localizador.','Times New Roman 12 · doble · bloque a 1,27 cm del margen','blockquote'],
 'apa-title':['Título','Título del trabajo, centrado y en negrita.','Times New Roman 12 · doble · centrado · negrita','p'],
 'apa-subtitle':['Subtítulo','Estilo auxiliar conservado de la plantilla. No es un nivel oficial de encabezado APA.','Times New Roman 12 · doble · centrado','p'],
 'apa-subtitle1':['Subtítulo 1','Estilo auxiliar en negrita. Usa Nivel 2 para integrarlo en la estructura APA.','Times New Roman 12 · doble · izquierda · negrita','p'],
 'apa-subtitle2':['Subtítulo 2','Estilo auxiliar. Usa Nivel 3 para integrarlo en la estructura APA.','Times New Roman 12 · doble · izquierda · negrita y cursiva','p'],
 h1:['Nivel 1','Sección principal. APA no exige numerar los encabezados.','Centrado · negrita · texto en el párrafo siguiente','h1'],
 h2:['Nivel 2','Subsección dentro de un nivel 1.','Izquierda · negrita · texto en el párrafo siguiente','h2'],
 h3:['Nivel 3','Subsección dentro de un nivel 2.','Izquierda · negrita y cursiva · texto en el párrafo siguiente','h3'],
 h4:['Nivel 4','Encabezado integrado al párrafo. Escribe el cuerpo después del punto.','Sangría 1,27 cm · encabezado en negrita · punto final · texto seguido','h4'],
 h5:['Nivel 5','Encabezado integrado de quinto nivel. El cuerpo continúa sin negrita ni cursiva.','Sangría 1,27 cm · encabezado en negrita y cursiva · punto final · texto seguido','h5'],
 reference:['Referencia','Entrada bibliográfica. Para vincularla con citas utiliza el gestor de referencias.','Times New Roman 12 · doble · sangría francesa 1,27 cm','p']};
let selectedStyle='apa-normal';
function renderStyles(){const groups=[['Texto',['apa-normal','apa-noindent','blockquote']],['Títulos',['apa-title','apa-subtitle','apa-subtitle1','apa-subtitle2']],['Encabezados APA',['h1','h2','h3','h4','h5']]];$('stylesPanel').innerHTML=groups.map(([label,items])=>`<div class="side-title">${label}</div>${items.map(k=>`<button class="style-item" data-style="${k}" onclick="applyStyle('${k}')">${stylesAPA[k][0]}${k==='apa-normal'?'<small>Primera línea · 1,27 cm</small>':''}</button>`).join('')}`).join('')+'<div class="side-title">Elementos</div><button class="style-item" onclick="insertApaTable()">＋ Tabla APA</button><button class="style-item" onclick="insertFigure()">＋ Figura APA</button><button class="style-item" onclick="insertCitation()">＋ Cita</button><button class="style-item" onclick="applyStyle(\'reference\')">Referencia — estilo</button><button class="style-item" onclick="openReferenceManager()">Biblioteca de referencias</button>';$('stylesPanel').insertAdjacentHTML('afterbegin','<div id="styleInfoSmall" class="card compact-style-info"></div>');showStyleInfo('apa-normal')}
function showStyleInfo(key){if(!stylesAPA[key])return;selectedStyle=key;const s=stylesAPA[key];$('styleInfo').innerHTML=`<div class="eyebrow">Estilo seleccionado</div><h3 style="margin-top:10px">${s[0]}</h3><p>${s[1]}</p><div class="divider"></div><p>${s[2]}</p><button class="btn" style="width:100%;margin-top:10px" onclick="applyStyle('${key}')">Aplicar estilo</button>`;if($('styleInfoSmall'))$('styleInfoSmall').innerHTML=$('styleInfo').innerHTML;document.querySelectorAll('[data-style]').forEach(b=>b.classList.toggle('chosen',b.dataset.style===key))}
function closestBlock(node){if(node?.nodeType===3)node=node.parentElement;while(node&&node!==editor){if(node.matches('p,h1,h2,h3,h4,h5,blockquote,li,.apa-title,.apa-subtitle,.apa-subtitle1,.apa-subtitle2'))return node;if(node.parentElement?.matches('.page-body')&&!node.matches('.cover,.table-wrap,.figure-wrap,.toc,.page-break'))return node;node=node.parentElement}return null}
function selectedBlocks(){if(!restoreSelection())return [];const r=getSelection().getRangeAt(0);if(r.collapsed){const n=closestBlock(r.startContainer);return n?[n]:[]}return [...editor.querySelectorAll('p,h1,h2,h3,h4,h5,blockquote,li,.apa-title,.apa-subtitle,.apa-subtitle1,.apa-subtitle2')].filter(n=>!n.closest('.cover,.table-wrap,.figure-wrap,.toc')&&r.intersectsNode(n)&&!(r.endOffset===0&&n.contains(r.endContainer)))}
function applyStyle(key){if(!stylesAPA[key])return;showStyleInfo(key);const blocks=selectedBlocks();if(!blocks.length){toast('Coloca el cursor en un párrafo o selecciona el texto que deseas formatear.');return}let last;blocks.forEach(b=>{if(b.closest('.cover,.table-wrap,.figure-wrap,.toc'))return;const n=document.createElement(stylesAPA[key][3]);n.className=key;if(b.id)n.id=b.id;for(const key of ['sectionKey','templatePrompt'])if(b.dataset[key])n.dataset[key]=b.dataset[key];n.innerHTML=b.innerHTML;n.querySelectorAll('.runin').forEach(s=>s.replaceWith(...s.childNodes));if(key==='h4'||key==='h5'){const span=document.createElement('span');span.className='runin';span.append(...n.childNodes);if(!span.textContent.trim().endsWith('.'))span.append('.');n.append(span,document.createTextNode(' '));}b.replaceWith(n);last=n});if(last)setCaret(last);$('styleSelect').value='';changed();toast('Estilo aplicado: '+stylesAPA[key][0]);markProgress(2)}
function cmd(c,v=null){if(!restoreSelection())return toast('Selecciona primero texto en el documento.');document.execCommand(c,false,v);rememberSelection();changed()}
function insertAtCursor(html){if(!currentId)return openNewDocWizard();restoreSelection();const t=document.createElement('template');t.innerHTML=html;const nodes=[...t.content.childNodes];const isBlock=nodes.some(n=>n.nodeType===1&&n.matches('p,div,h1,h2,h3,h4,h5,blockquote,ul,ol,table'));if(!savedRange||!editor.contains(savedRange.startContainer)){const body=editor.querySelector('.page:last-child .page-body')||editor;nodes.forEach(n=>body.append(n));setCaret(nodes.at(-1));changed();return}const r=savedRange.cloneRange();r.deleteContents();if(isBlock){let anchor=closestBlock(r.startContainer);if(!anchor){const el=r.startContainer.nodeType===3?r.startContainer.parentElement:r.startContainer;anchor=el.closest('.table-wrap,.figure-wrap,.cover,.toc')}if(anchor){const container=anchor.closest('.table-wrap,.figure-wrap,.cover,.toc');if(container)anchor=container;let tail=null;if(!container&&anchor.contains(r.startContainer)){const after=document.createRange();after.setStart(r.startContainer,r.startOffset);after.setEnd(anchor,anchor.childNodes.length);tail=anchor.cloneNode(false);tail.removeAttribute('id');tail.append(after.extractContents())}let point=anchor;for(const n of nodes){point.after(n);point=n}if(tail&&(tail.textContent||tail.querySelector('img')))point.after(tail)}else{const body=r.startContainer.nodeType===1&&r.startContainer.matches('.page-body')?r.startContainer:editor.querySelector('.page:last-child .page-body');nodes.forEach(n=>body.append(n))}}else{const f=document.createDocumentFragment();nodes.forEach(n=>f.append(n));r.insertNode(f)}const last=nodes.at(-1);if(last?.nodeType===1&&last.contentEditable==='false'){const range=document.createRange();range.setStartAfter(last);range.collapse(true);getSelection().removeAllRanges();getSelection().addRange(range);savedRange=range}else setCaret(last);changed()}
function insertParagraph(){insertAtCursor('<p class="apa-normal"><br></p>')}
function insertHeading(level){insertAtCursor(`<h${level}>Nuevo encabezado</h${level}><p class="apa-normal"><br></p>`)}
function headingText(h){return h.querySelector('.runin')?.textContent.trim()||h.textContent.trim()||'Sin título'}
function headings(){return [...editor.querySelectorAll('h1,h2,h3,h4,h5')].filter(n=>!n.dataset.continuation)}
function updateOutline(){const hs=headings();$('outline').innerHTML=hs.length?'':'<p class="help">Agrega secciones para organizar tu trabajo.</p>';hs.forEach(h=>{h.id=h.id||uid();const row=document.createElement('div');row.className='outline-row';const b=document.createElement('button');b.className='l'+h.tagName.slice(1);b.textContent=headingText(h);b.title=b.textContent;b.onclick=()=>navigateHeading(h.id);const more=document.createElement('button');more.className='more';more.textContent='⋮';more.setAttribute('aria-label','Organizar '+headingText(h));more.onclick=()=>sectionMenu(h.id);row.append(b,more);$('outline').append(row)});updateTOC();updateStats()}
function navigateHeading(id){showEditor();const h=$(id);h?.scrollIntoView({behavior:'smooth',block:'center'});if(h)setCaret(h);if(innerWidth<781)document.querySelector('.sidebar').classList.remove('open')}
function sectionMenu(id){const h=$(id);dialog('Organizar sección',`<div class="field"><label for="sectionName">Nombre</label><input id="sectionName" value="${esc(headingText(h))}"></div><p class="small">Mover o eliminar incluye el contenido y los subencabezados de esta sección.</p><div class="field-row"><button class="btn" onclick="moveSection('${id}',-1)">↑ Subir</button><button class="btn" onclick="moveSection('${id}',1)">↓ Bajar</button><button class="btn" onclick="removeSection('${id}')">Eliminar sección</button></div>`,`<button class="btn primary" onclick="renameSection('${id}')">Guardar nombre</button>`)}
function normalizeForStructure(){const list=unmerge(logicalNodes());editor.replaceChildren(...list);savedRange=null;return list}
function sectionRange(list,h){const start=list.indexOf(h),level=Number(h.tagName.slice(1));let end=start+1;while(end<list.length&&!(list[end].matches('h1,h2,h3,h4,h5')&&Number(list[end].tagName.slice(1))<=level))end++;return {start,end}}
function renameSection(id){const h=$(id),name=$('sectionName').value.trim();if(!name)return;const span=h.querySelector('.runin');if(span)span.textContent=name.replace(/\.?$/,'.');else h.textContent=name;closeModal('dialogModal');changed()}
function moveSection(id,dir){const h=$(id),list=normalizeForStructure(),{start,end}=sectionRange(list,h),level=h.tagName;let target;if(dir<0){for(let i=start-1;i>=0;i--){if(list[i].tagName===level){target=list[i];break}if(list[i].matches('h1,h2,h3,h4,h5')&&Number(list[i].tagName.slice(1))<Number(level.slice(1)))break}}else{const next=list[end];if(next?.tagName===level){const r=sectionRange(list,next);target=list[r.end]||null}else target=undefined}if(target===undefined){paginate();return toast('No hay otra sección del mismo nivel en esa dirección.')}const group=list.slice(start,end);group.forEach(n=>editor.insertBefore(n,target));paginate();changed();closeModal('dialogModal')}
function removeSection(id){if(!confirm('¿Eliminar esta sección y todo su contenido? Puedes deshacer desde la barra del editor.'))return;const h=$(id),list=normalizeForStructure(),r=sectionRange(list,h);list.slice(r.start,r.end).forEach(n=>n.remove());if(!editor.children.length)editor.innerHTML='<p class="apa-normal"><br></p>';closeModal('dialogModal');paginate();changed()}
function addSection(){dialog('Agregar sección','<div class="field"><label for="newSectionName">Nombre de la sección</label><input id="newSectionName" placeholder="Ej. Marco teórico"></div><div class="field" style="margin-top:12px"><label for="newSectionLevel">Nivel</label><select id="newSectionLevel"><option value="1">Nivel 1</option><option value="2">Nivel 2</option><option value="3">Nivel 3</option></select></div>','<button class="btn primary" onclick="commitSection()">Agregar al documento</button>')}
function commitSection(){const name=$('newSectionName').value.trim();if(!name)return;const level=$('newSectionLevel').value;closeModal('dialogModal');insertAtCursor(`<h${level}>${esc(name)}</h${level}><p class="apa-normal"><br></p>`)}
function generateTOC(){if(editor.querySelector('.toc'))return toast('El índice ya está insertado y se actualiza automáticamente.');insertAtCursor('<div class="toc" contenteditable="false"><div class="toc-title">Índice</div><div class="toc-items"></div></div><p class="apa-normal"><br></p>');updateTOC();paginate();toast('Índice insertado. APA no lo exige en todos los trabajos.')}
function updateTOC(){const toc=editor.querySelector('.toc-items');if(!toc)return;const html=headings().map(h=>{h.id=h.id||uid();const page=h.closest('.page')?.querySelector('.page-number')?.textContent||'–';return `<a href="#${h.id}" style="padding-left:${(Number(h.tagName.slice(1))-1)*12}px"><span>${esc(headingText(h))}</span><span>${page}</span></a>`}).join('');if(toc.innerHTML!==html)toc.innerHTML=html}
function openPaste(){dialog('Pegar texto','<p class="lead">Pega desde Word, Google Docs, PDF u otro editor. Se conservará el texto, sin formatos externos. Los saltos de línea se convertirán en párrafos.</p><div class="field"><label for="pasteText">Texto que deseas incorporar</label><textarea id="pasteText" style="min-height:220px"></textarea></div><label class="inline-check" style="margin-top:12px"><input id="replaceSelection" type="checkbox"> Reemplazar el texto seleccionado</label>','<button class="btn primary" onclick="commitPaste()">Insertar texto limpio</button>')}
function insertPlainText(text){if(!text)return;const lines=text.replace(/\r\n?/g,'\n').split(/\n/);if(lines.length===1)insertAtCursor(esc(text));else insertAtCursor(lines.map(l=>`<p class="apa-normal">${esc(l)||'<br>'}</p>`).join(''))}
function commitPaste(){const text=$('pasteText').value,replace=$('replaceSelection').checked;if(replace&&savedRange&&!savedRange.collapsed&&!confirm('¿Reemplazar la selección por este texto?'))return;if(!replace&&savedRange)savedRange.collapse(false);closeModal('dialogModal');insertPlainText(text)}
function formatSelection(){dialog('Formatear texto seleccionado','<p class="lead">Cambia el estilo de los párrafos seleccionados; no elimina el texto. Coloca primero el cursor o selecciona contenido en la hoja.</p>'+['apa-normal','apa-noindent','apa-title','h1','h2','h3','h4','h5','reference'].map(k=>`<button class="btn" style="margin:4px" onclick="closeModal('dialogModal');applyStyle('${k}')">${stylesAPA[k][0]}</button>`).join(''))}
function detectContext(){const s=getSelection(),el=s.anchorNode?.nodeType===3?s.anchorNode.parentElement:s.anchorNode;activeElement=el?.closest?.('.table-wrap,.figure-wrap,.page-break,.toc')||null;renderElementTools();if(el?.closest('.reference'))selectedStyle='reference'}
function renderElementTools(){const bar=$('elementTools');if(!activeElement?.isConnected){bar.classList.remove('visible');return}let html='';if(activeElement.matches('.table-wrap'))html='<b>Tabla APA</b> <button class="btn" onclick="tableAction(\'row+\')">＋ Fila</button><button class="btn" onclick="tableAction(\'row-\')">− Fila</button><button class="btn" onclick="tableAction(\'col+\')">＋ Columna</button><button class="btn" onclick="tableAction(\'col-\')">− Columna</button><button class="btn" onclick="editTable()">Número, título y nota</button><button class="btn" onclick="tableAction(\'duplicate\')">Duplicar</button>';if(activeElement.matches('.figure-wrap'))html='<b>Figura APA</b> <button class="btn" onclick="changeFigureImage()">Cambiar imagen</button><button class="btn" onclick="editFigure()">Editar datos</button>';if(activeElement.matches('.toc'))html='<b>Índice automático</b>';if(activeElement.matches('.page-break'))html='<b>Salto de página</b>';bar.innerHTML=html+'<button class="btn" onclick="deleteActiveElement()">Eliminar</button><button class="btn" onclick="openTutor()">¿Cómo se hace?</button>';bar.classList.add('visible')}
function wholeElement(){if(!activeElement?.isConnected)return;const flow=activeElement.dataset.flow;if(flow){const nodes=[...editor.querySelectorAll('[data-flow]')].filter(n=>n.dataset.flow===flow);activeElement=unmerge(nodes)[0]||activeElement}}
function deleteActiveElement(){if(!activeElement?.isConnected)return;if(!confirm('¿Eliminar este elemento?'))return;wholeElement();activeElement.remove();activeElement=null;renderElementTools();changed()}
function openTutor(){let title='¿Cómo se hace?',text;if(activeElement?.matches('.table-wrap'))text='Las tablas necesitan número en negrita y título en cursiva. Haz clic en una celda para escribir. La barra contextual permite agregar o eliminar la fila o columna seleccionada. Las notas solo son necesarias cuando hay algo que explicar.';else if(activeElement?.matches('.figure-wrap'))text='Carga una imagen de tu dispositivo. Incluye un título descriptivo y un texto alternativo. Si adaptas una imagen ajena, comprueba la licencia y atribúyela en la nota y las referencias.';else if(selectedStyle==='reference')text='Las referencias utilizan sangría francesa de 1,27 cm. Registra la fuente en la biblioteca para reutilizarla en tus citas. La biblioteca ordena las entradas alfabéticamente.';else text=stylesAPA[selectedStyle][1]+' '+stylesAPA[selectedStyle][2]+'. Selecciona un párrafo y pulsa el estilo en el panel izquierdo. Usa el paso sugerido a la derecha si no sabes cómo continuar.';dialog(title,`<p class="lead">${text}</p><div class="notice">APA define el formato y la atribución de fuentes. Tu institución puede añadir requisitos de estructura, portada o entrega. Compruébalos con tu docente.</div>`,'<button class="btn primary" onclick="closeModal(\'dialogModal\');openGuide()">Aprender con ejemplos</button>')}
const steps=['Completa la portada','Escribe la introducción','Organiza tus encabezados','Desarrolla tus párrafos','Agrega citas','Completa las referencias','Añade tablas o figuras, si las necesitas','Revisa el formato APA','Exporta tu trabajo'];
function markProgress(i){if(!progress.includes(i))progress.push(i);updateProgress();scheduleSave()}
function updateProgress(){const i=steps.findIndex((_,n)=>!progress.includes(n));const current=i<0?8:i;$('nextStep').innerHTML=`<div class="step-counter">TU SIGUIENTE PASO · ${Math.min(progress.length+1,9)} DE 9</div><h3>${steps[current]}</h3><p>No necesitas hacerlo todo a la vez. Avanza a tu ritmo.</p><button class="btn primary" onclick="stepAction(${current})">${current===8?'Exportar':'Continuar'} →</button> <button class="btn ghost" onclick="markProgress(${current})" title="Marcar este paso como completado">✓ Hecho</button><div class="progress-dots">${steps.map((s,n)=>`<span title="${s}" class="${progress.includes(n)?'done':n===current?'current':''}">${progress.includes(n)?'✓':n+1}</span>`).join('')}</div>`}
function stepAction(i){if(i===0)openSettings();if(i===1){const h=headings().find(h=>/introducci[oó]n/i.test(h.textContent));if(h)navigateHeading(h.id);else addSection()}if(i===2)switchSidebar('styles');if(i===3){showEditor();editor.focus()}if(i===4)insertCitation();if(i===5)openReferenceManager();if(i===6)insertApaTable();if(i===7)runChecker();if(i===8)printDocument()}
