/* Experiencia Studio: preferencias locales, herramientas reales y ayuda progresiva. */
let studioPrefs={answered:[],goal:800},pendingWordImport=null,findHits=[],findPosition=-1;
try{const s=JSON.parse(localStorage.getItem('pma7-studio-prefs')||'{}');studioPrefs.answered=Array.isArray(s.answered)?s.answered.filter(n=>Number.isInteger(n)&&n>=0&&n<13):[];studioPrefs.goal=Number(s.goal)>0?Math.min(100000,Number(s.goal)):800}catch(e){}
function saveStudioPrefs(){try{localStorage.setItem('pma7-studio-prefs',JSON.stringify(studioPrefs))}catch(e){toast('Preferencias solo para esta sesión: el navegador no permite guardarlas.')}}
function renderStudioStats(){if($('studioDocs'))$('studioDocs').textContent=docs.length;if($('studioLessons'))$('studioLessons').textContent=studioPrefs.answered.length+'/13';if($('runtimeBadge'))$('runtimeBadge').textContent='Editor listo · guardado local';}
function studioHome(){showHome();window.scrollTo({top:0,behavior:'smooth'})}
function setRibbon(tab){document.querySelectorAll('.ribbon-tab').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.ribbonTab===tab)));document.querySelectorAll('.toolbar .group').forEach(g=>g.hidden=tab!=='Todas'&&!g.dataset.ribbon.split(' ').includes(tab));}
function toggleFocusMode(){const app=document.querySelector('.app');app.classList.toggle('focus-mode');$('focusToggle').setAttribute('aria-pressed',String(app.classList.contains('focus-mode')));$('focusToggle').textContent=app.classList.contains('focus-mode')?'Salir de concentración':'Concentración';requestAnimationFrame(()=>setZoom(viewZoom));}
function filterHomeModels(){const q=norm($('homeModelSearch').value),category=$('homeModelCategory').value;let n=0;document.querySelectorAll('.home-word-model').forEach(card=>{const ok=norm(card.textContent).includes(q)&&(category==='Todas'||card.dataset.category===category)&&(homeFamily==='all'||card.dataset.family===homeFamily);card.hidden=!ok;if(ok)n++});$('homeModelCount').textContent=n+' modelos disponibles';if($('homeModelEmpty'))$('homeModelEmpty').hidden=n!==0;}
function openWritingGoal(){if(!currentId)return openNewDocWizard();const words=editor.innerText.trim().split(/\s+/).filter(Boolean).length;dialog('Tu meta de escritura',`<p class="lead">Una meta personal, no un requisito APA ni una medida de calidad.</p><div class="studio-metric"><b>${words}</b> palabras aproximadas en el documento completo</div><div class="field"><label for="writingGoal">Meta de palabras</label><input id="writingGoal" type="number" min="1" max="100000" value="${studioPrefs.goal}"></div><p>Esta cuenta incluye portada, referencias y tablas. Para un límite institucional comprueba qué partes deben contarse.</p>`,'<button class="btn primary" onclick="saveWritingGoal()">Guardar meta</button>')}
function saveWritingGoal(){const n=Number($('writingGoal').value);if(!Number.isInteger(n)||n<1||n>100000)return toast('Escribe un número entre 1 y 100 000.');studioPrefs.goal=n;saveStudioPrefs();closeModal('dialogModal');toast('Meta personal guardada: '+n+' palabras.')}
function openFind(){if(!currentId)return openDocuments();findHits=[];findPosition=-1;dialog('Buscar y reemplazar',`<p class="lead">Busca texto en el documento. Las citas vinculadas, referencias gestionadas, el índice y la portada no se reemplazan automáticamente.</p><div class="field"><label for="findText">Buscar texto literal</label><input id="findText" oninput="findPosition=-1;scanFind()"></div><div class="field"><label for="replaceText">Reemplazar por</label><input id="replaceText"></div><label class="inline-check"><input type="checkbox" id="findCase" onchange="findPosition=-1;scanFind()"> Distinguir mayúsculas</label><p id="findStatus" role="status">Escribe el texto que deseas buscar.</p><p class="small">Se buscan coincidencias dentro de cada fragmento de formato; una palabra dividida por negritas o cursivas puede requerir revisión manual. Puedes deshacer los reemplazos.</p>`,'<button class="btn" onclick="nextFound()">Siguiente coincidencia</button><button class="btn primary" onclick="replaceFound(false)">Reemplazar una</button><button class="btn" onclick="replaceFound(true)">Reemplazar todas</button>')}
function scanFind(){findHits=[];const query=$('findText')?.value;if(!query){if($('findStatus'))$('findStatus').textContent='Escribe el texto que deseas buscar.';return}const exact=$('findCase').checked,pattern=new RegExp(query.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),exact?'gu':'giu');const walker=document.createTreeWalker(editor,NodeFilter.SHOW_TEXT);let node;while(node=walker.nextNode()){if(node.parentElement.closest('.cover,.toc,.citation,.reference[data-ref-id],.page-number,.page-break,.selection-marker'))continue;for(const match of node.data.matchAll(pattern)){findHits.push({node,start:match.index,length:match[0].length});if(findHits.length>=10000)break}if(findHits.length>=10000)break}if($('findStatus'))$('findStatus').textContent=findHits.length+' coincidencia(s) en texto editable.';return findHits}
function nextFound(){scanFind();if(!findHits.length)return;findPosition=(findPosition+1)%findHits.length;const hit=findHits[findPosition];const r=document.createRange();r.setStart(hit.node,hit.start);r.setEnd(hit.node,hit.start+hit.length);savedRange=r;getSelection().removeAllRanges();getSelection().addRange(r);hit.node.parentElement.scrollIntoView({block:'center',behavior:'smooth'});$('findStatus').textContent='Coincidencia '+(findPosition+1)+' de '+findHits.length+': '+hit.node.parentElement.textContent.slice(0,100)}
function replaceFound(all){scanFind();if(!findHits.length)return toast('No hay coincidencias para reemplazar.');const value=$('replaceText').value;if(all&&!confirm('¿Reemplazar '+findHits.length+' coincidencia(s)? Puedes deshacer el cambio.'))return;checkpoint();const chosen=all?[...findHits].reverse():[findHits[Math.max(0,Math.min(findPosition,findHits.length-1))]];for(const h of chosen)h.node.replaceData(h.start,h.length,value);savedRange=null;changed();checkpoint();findPosition=-1;scanFind();toast(chosen.length+' reemplazo(s) realizados sin quitar los estilos.')}
function renderPractice(i){const item=STUDIO_QUIZ[i];const box=document.createElement('section');box.className='practice-box';box.innerHTML=`<span class="mini-label">PRACTICA EN 20 SEGUNDOS</span><h3>${esc(item.q)}</h3><div class="practice-options">${item.options.map((t,n)=>`<button class="btn" onclick="answerPractice(${i},${n})">${esc(t)}</button>`).join('')}</div><p id="practiceFeedback" role="status">${studioPrefs.answered.includes(i)?'Ya respondiste correctamente este ejercicio. Puedes repetirlo.':'Sin calificaciones ni presión: comprueba si la idea quedó clara.'}</p><a class="btn" data-ready-word="guide" href="Guia_APA7_Estudio.docx" download>Descargar guía completa en Word</a>`;document.querySelector('#guide-learn .lesson-body')?.append(box);hydrateWordLinks(box)}
function answerPractice(i,n){const item=STUDIO_QUIZ[i],ok=n===item.correct;$('practiceFeedback').textContent=(ok?'¡Bien! ':'Inténtalo otra vez. ')+item.feedback;if(ok&&!studioPrefs.answered.includes(i)){studioPrefs.answered.push(i);saveStudioPrefs();renderStudioStats()}}
function openStartPath(){dialog('Tu ruta de trabajo, paso a paso',`<div class="start-path"><section><b>01 · Elige</b><p>Usa la plantilla normal para una tarea de curso o busca el modelo que corresponda a tu encargo.</p><button class="btn" onclick="closeModal('dialogModal');goToWordDownloads()">Ver plantillas</button></section><section><b>02 · Escribe</b><p>Completa los datos, redacta tus ideas y abre la guía del apartado cuando no sepas qué incluir.</p><button class="btn" onclick="closeModal('dialogModal');openNewDocWizard()">Crear documento</button></section><section><b>03 · Revisa</b><p>Comprueba contenido y fuentes. El revisor técnico ayuda, pero no certifica tu trabajo.</p><button class="btn" onclick="closeModal('dialogModal');runChecker()">Revisar mi trabajo</button></section><section><b>04 · Conserva</b><p>Descarga Word para entregar y Copia APA para recuperar tu biblioteca y continuar aquí.</p><button class="btn" onclick="openDownloads()">Elegir descarga</button></section></div>`,'<button class="btn" onclick="closeModal(\'dialogModal\');openGuide()">Aprender desde cero</button>')}
function chooseWordFile(){$('wordOpenFile').click()}
function normaliseImportedWord(html){const box=document.createElement('div');box.innerHTML=sanitize(html);box.querySelectorAll('p').forEach(p=>{if(!p.className&&!p.closest('table'))p.className='apa-normal'});box.querySelectorAll('h1,h2,h3,h4,h5').forEach(h=>{h.className=h.tagName.toLowerCase();if(h.matches('h4,h5')){const first=h.querySelector('strong,b');const span=document.createElement('span');span.className='runin';if(first){span.innerHTML=first.innerHTML;first.replaceWith(span)}else{span.innerHTML=h.innerHTML;h.replaceChildren(span)}if(!span.textContent.trim().endsWith('.'))span.append('.')}});
const lines=[...box.querySelectorAll(':scope > .cover-line')];if(lines.length&&lines[0].previousElementSibling?.matches('.apa-title')){const title=lines[0].previousElementSibling,cover=document.createElement('div');cover.className='cover';title.before(cover);const titleNode=document.createElement('div');titleNode.className='cover-title';titleNode.innerHTML=title.innerHTML;cover.append(titleNode,...lines);title.remove();lines.forEach(p=>p.removeAttribute('class'))}
const wrap=(node,kind,index)=>{const outer=document.createElement('div');outer.className=kind+'-wrap';const prev=node.previousElementSibling,title=prev?.matches('.element-title')?prev:null;const num=(title||node).previousElementSibling;const label=num?.matches('.element-number')?num:null;const next=node.nextElementSibling,note=next?.matches('.element-note')?next:null;node.before(outer);for(const [suffix,original,fallback] of [['label',label,(kind==='table'?'Tabla ':'Figura ')+(index+1)],['title',title,'']]){const el=document.createElement('div');el.className=kind+'-'+suffix;el.innerHTML=original?original.innerHTML:esc(fallback);outer.append(el);original?.remove()}outer.append(node);const nt=document.createElement('div');nt.className=kind+'-note';nt.innerHTML=note?.innerHTML||'';outer.append(nt);note?.remove()};
[...box.querySelectorAll('table')].filter(t=>!t.parentElement.closest('table')).forEach((t,i)=>wrap(t,'table',i));[...box.querySelectorAll('img')].filter(img=>!img.closest('table')).forEach((img,i)=>{const n=img.parentElement.matches('p')&&img.parentElement.childNodes.length===1?img.parentElement:img;wrap(n,'figure',i)});return box.innerHTML}
async function importWordFile(file){if(!file)return;try{if(!/\.docx$/i.test(file.name)||file.size>20*1024*1024)throw Error('Elige un DOCX de hasta 20 MB; no se admiten DOC, DOCM ni archivos protegidos.');toast('Leyendo Word localmente…');const result=await APAImport.convert(await file.arrayBuffer());const html=normaliseImportedWord(result.value);if(!html.trim())throw Error('No se encontró contenido de texto importable.');pendingWordImport={name:file.name.replace(/\.docx$/i,''),html};dialog('Tu Word está listo para importar',`<p class="lead"><b>${esc(pendingWordImport.name)}</b></p><p>Se abrirá como un documento nuevo en esta aplicación. Tu trabajo actual se conservará por separado.</p><div class="notice">Se recuperan texto, estilos reconocidos, listas, tablas e imágenes compatibles y se aplica la base APA 7. La distribución de páginas se recalcula.</div><p class="notice warn">No es una reproducción exacta de Word: revisa ecuaciones, comentarios, cambios controlados, formas, pies de página y campos complejos. Las citas importadas no se convierten automáticamente en biblioteca de referencias.</p>${result.messages.length?`<details><summary>${result.messages.length} aviso(s) del conversor</summary>${result.messages.slice(0,30).map(m=>'<p class="small">'+esc(m.message)+'</p>').join('')}</details>`:''}`,'<button class="btn" onclick="pendingWordImport=null;closeModal(\'dialogModal\')">Cancelar</button><button class="btn primary" onclick="commitWordImport()">Importar como documento nuevo</button>')}catch(e){toast('No se pudo abrir el Word: '+e.message)}finally{if($('wordOpenFile'))$('wordOpenFile').value='';if($('openFile'))$('openFile').value=''}}
function commitWordImport(){if(!pendingWordImport)return;if(currentId&&!saveState())return toast('Guarda una copia del trabajo actual antes de importar.');const data=pendingWordImport;loadDoc({id:uid(),name:data.name,html:data.html,refs:[],config:{type:'Importado de Word',institutionRules:''},cover:{},progress:[]});pendingWordImport=null;closeModal('dialogModal');saveState();toast('Word importado como copia nueva. Revisa formato, elementos y referencias.')}
function bootStudio(){renderStudioStats();window.addEventListener('error',()=>{if($('runtimeBadge'))$('runtimeBadge').textContent='Revisa el navegador · los enlaces Word directos siguen disponibles'});document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='f'&&!document.querySelector('.app').classList.contains('hidden')){e.preventDefault();openFind()}})}
