/* Asistente original de cinco pasos, ampliado con jerarquía y procedencia. */
const legacyModels={'Trabajo académico':'academico','Ensayo':'ensayo','Informe':'informe','Monografía':'monografia','Proyecto':'upeu-perfil','Investigación':'upeu-articulo','Trabajo de Enfermería':'enfermeria','Otro':'otro'};
const templates=Object.fromEntries(Object.entries(legacyModels).map(([label,id])=>[label,getModel(id).sections.map(s=>s.name)]));
const coverFields=[['Title','Título'],['Author','Estudiante / autores'],['Institution','Institución'],['School','Facultad / Escuela'],['Course','Asignatura / programa'],['Professor','Docente / asesor'],['Date','Fecha']];
let wizard={step:0,type:'Trabajo académico',data:{},cover:true,sections:[]};
function openNewDocWizard(id='academico'){const m=getModel(id)||getModel('academico');wizard={step:0,type:m.label,modelId:m.id,data:{Date:new Date().toLocaleDateString('es-PE',{day:'numeric',month:'long',year:'numeric'}),Institution:m.category==='UPeU'?'Universidad Peruana Unión':''},cover:m.cover,toc:m.toc,prompts:false,ack:false,journal:'',sections:m.sections.map(s=>({...s,enabled:!s.optional}))};renderWizard();showModal('wizardModal')}
function wizardModelNote(m){return `<details class="model-detail" style="margin-top:14px"><summary>Procedencia y límites de este modelo · ${esc(m.org)}</summary><p>${esc(m.why)}</p><p class="small">Fuente consultada ${esc(m.checked)} · ${esc(m.status)}</p>${m.warnings.map(w=>`<p class="notice warn">${esc(w)}</p>`).join('')}${sourceLinks(m.sources)}</details>`}
function renderWizard(){const s=wizard.step,m=getModel(wizard.modelId)||getModel('academico');let body='';
 if(s===0)body='<p class="lead">Selecciona la estructura que corresponda a tu encargo. APA define presentación y atribución; no impone un mismo esquema a todos los géneros.</p><div class="type-grid">'+MODEL_CATALOG.filter(x=>!x.historical||x.id===wizard.modelId).map(x=>`<button class="type-option ${wizard.modelId===x.id?'selected':''}" aria-label="${esc(x.label)}" aria-pressed="${wizard.modelId===x.id}" onclick="chooseTemplate('${x.id}')">${esc(x.label)}${wizard.modelId===x.id?' ✓':''}<small>${esc(x.org)}</small></button>`).join('')+'</div>'+wizardModelNote(m);
 if(s===1)body='<div class="form-grid">'+coverFields.map(([key,label])=>field('wiz'+key,label,wizard.data[key]||'')).join('')+(m.institutional?field('wizJournal','Revista / guía del programa (si corresponde)',wizard.journal||''):'')+'</div><p class="small">Los datos se guardan únicamente en este navegador. Nunca se envían a las fuentes consultadas.</p>';
 if(s===2)body=`<label class="inline-check"><input type="checkbox" id="wizIncludeCover" ${wizard.cover?'checked':''}> Incluir portada de estudiante</label><p class="lead">${m.cover?'El título se mostrará centrado y en negrita, seguido de tus datos académicos.':'Este tipo de manuscrito suele empezar con título y autoría, sin una portada estudiantil separada. Confirma si requiere anonimato.'}</p><div class="notice">Esta portada es una base APA para estudiantes, no un formulario oficial de titulación. Los preliminares, actas y declaraciones institucionales se obtienen del programa correspondiente.</div><label class="inline-check" style="margin-top:12px"><input id="wizIncludeTOC" type="checkbox" ${wizard.toc?'checked':''}> Incluir índice automático</label><p class="small">El índice es opcional según el encargo; APA no lo exige en todos los trabajos.</p>`;
 if(s===3)body='<p class="lead">Activa, renombra, agrega y reordena apartados. Los opcionales empiezan desactivados. Si cambias la estructura o su numeración, confirma que tu guía lo permita.</p><div id="wizSectionList" class="guided-sections">'+wizard.sections.map((x,i)=>`<div class="guided-section"><div class="section-config"><input aria-label="Incluir ${esc(x.name)}" type="checkbox" ${x.enabled?'checked':''} onchange="wizard.sections[${i}].enabled=this.checked"><input type="text" aria-label="Nombre de sección ${i+1}" value="${esc(x.name)}" oninput="wizard.sections[${i}].name=this.value"><select ${x.kind==='keywords'?'disabled title="Etiqueta en cursiva; no es encabezado"':''} aria-label="Nivel de sección ${i+1}" onchange="wizard.sections[${i}].level=Number(this.value)">${x.kind==='keywords'?'<option>Etiqueta</option>':[1,2,3,4,5].map(l=>`<option value="${l}" ${l===x.level?'selected':''}>Nivel ${l}</option>`).join('')}</select><button class="btn" title="Subir sección" onclick="moveWizardSection(${i},-1)">↑</button><button class="btn" title="Bajar sección" onclick="moveWizardSection(${i},1)">↓</button><button class="btn" title="Quitar sección" onclick="wizard.sections.splice(${i},1);renderWizard()">×</button></div><details><summary class="small">${x.optional?'Opcional · ':''}¿Qué escribir aquí?</summary><p class="small">${esc(x.guide||'Adapta este apartado a tu consigna.')}</p></details></div>`).join('')+'</div><button class="btn" style="margin-top:12px" onclick="addWizardSection()">＋ Agregar sección</button><details style="margin-top:15px"><summary>Agregar secciones de Enfermería</summary><div class="field-row" style="margin-top:10px">'+templates['Trabajo de Enfermería'].map((t,i)=>`<button class="btn" onclick="addWizardNursing(${i})">${esc(t)}</button>`).join('')+'</div></details><label class="inline-check" style="margin-top:16px"><input type="checkbox" '+(wizard.prompts?'checked':'')+' onchange="wizard.prompts=this.checked"> Incluir indicaciones entre corchetes dentro del documento</label><p class="small">Recomendado: dejarlo desactivado. Tendrás la guía al lado, sin mezclar instrucciones con tu trabajo.</p>';
 if(s===4)body=`<div class="notice"><b>${esc(wizard.data.Title||'Documento académico')}</b><br>${esc(wizard.type)} · ${wizard.cover?'Con portada':'Sin portada'} · ${wizard.toc?'Con índice':'Sin índice'}<br>${wizard.sections.filter(x=>x.enabled).map(x=>esc(x.name)).join(' → ')||'Documento en blanco'}</div><p class="lead">Carta · márgenes 2,54 cm · Times New Roman 12 · interlineado doble.</p><p class="small">Tu documento actual se conservará por separado. La ayuda se ${wizard.prompts?'incluye entre corchetes: reemplázala antes de entregar':'mantiene fuera de la hoja'}. Descarga copias para proteger tu trabajo.</p>${m.institutional?`<div class="notice warn">${esc(m.warnings.join(' '))}</div><label class="inline-check" style="margin-top:12px"><input type="checkbox" id="wizAcknowledge" ${wizard.ack?'checked':''} onchange="wizard.ack=this.checked"> Entiendo que es una adaptación APA, no el formato oficial completo; confirmaré versión y requisitos con mi programa o revista.</label>`:''}`;
 $('wizardContent').innerHTML=`<div class="eyebrow">NUEVO DOCUMENTO · PASO ${s+1} DE 5</div><h2 style="margin-top:9px">${['¿Qué trabajo vas a crear?','Los datos de tu trabajo','Elige tu portada','Organiza tu contenido','Todo listo para empezar'][s]}</h2><div class="wizard-steps">${['Tipo','Datos','Portada','Estructura','Crear'].map((t,i)=>`<span class="${i<=s?'active':''}">${i+1}. ${t}</span>`).join('')}</div>${body}`;
 $('wizardFooter').innerHTML=`<button class="btn" onclick="${s===0?"closeModal('wizardModal')":"wizardNext(-1)"}">${s===0?'Cancelar':'← Anterior'}</button><button class="btn primary" onclick="${s===4?'createFromWizard()':'wizardNext(1)'}">${s===4?'Crear documento':'Continuar →'}</button>`;
}
function chooseTemplate(t){const m=getModel(legacyModels[t]||t)||MODEL_CATALOG.find(m=>m.label===t);if(!m)return;wizard.type=m.label;wizard.modelId=m.id;wizard.cover=m.cover;wizard.toc=m.toc;wizard.ack=false;wizard.sections=m.sections.map(s=>({...s,enabled:!s.optional}));if(m.category==='UPeU'&&!wizard.data.Institution)wizard.data.Institution='Universidad Peruana Unión';renderWizard()}
function wizardNext(dir){if(wizard.step===1){coverFields.forEach(([k])=>wizard.data[k]=$('wiz'+k).value.trim());wizard.journal=$('wizJournal')?.value.trim()||'';if(dir>0&&!wizard.data.Title)return toast('Escribe un título para tu trabajo.')}if(wizard.step===2){wizard.cover=$('wizIncludeCover').checked;wizard.toc=$('wizIncludeTOC').checked}wizard.step+=dir;renderWizard()}
function moveWizardSection(i,d){const j=i+d;if(j<0||j>=wizard.sections.length)return;[wizard.sections[i],wizard.sections[j]]=[wizard.sections[j],wizard.sections[i]];renderWizard()}
function addWizardSection(){wizard.sections.push({key:uid(),name:'Nueva sección',level:1,enabled:true,guide:'Desarrolla este apartado según tu encargo.',check:'¿Aporta al objetivo?',optional:false});renderWizard()}
function addWizardNursing(i){const s=getModel('enfermeria').sections[i];wizard.sections.push({...s,key:uid(),enabled:true});renderWizard()}
function coverHTML(data){return `<div class="cover" id="${uid()}"><div class="cover-title">${esc(data.Title||'Título del trabajo académico')}</div>${coverFields.slice(1).map(([k])=>`<p>${esc(data[k]||'')}</p>`).join('')}</div>`}
function createFromWizard(){const m=getModel(wizard.modelId)||getModel('academico');if(m.institutional&&!wizard.ack)return toast('Confirma que comprendes la diferencia entre adaptación APA y formato institucional.');if(currentId&&!saveState()&&!confirm('No se pudo guardar el trabajo actual. Descarga una copia antes de continuar. ¿Crear otro documento de todos modos?'))return;const titleBlock=!wizard.cover&&!['academico','otro','enfermeria','ensayo','informe','monografia'].includes(m.id)?`<p class="apa-title">${esc(wizard.data.Title||'Título del manuscrito')}</p>${wizard.data.Author?`<p class="apa-noindent">${esc(wizard.data.Author)}${wizard.data.Institution?' · '+esc(wizard.data.Institution):''}</p>`:''}`:'';const toc=wizard.toc?'<div class="toc" contenteditable="false"><div class="toc-title">Índice</div><div class="toc-items"></div></div><div class="page-break" contenteditable="false" aria-label="Salto de página"></div>':'';const html=(wizard.cover?coverHTML(wizard.data):titleBlock)+toc+wizard.sections.filter(x=>x.enabled&&x.name.trim()).map(x=>{const level=Math.max(1,Math.min(5,Number(x.level)||1));const text=x.name.trim();if(x.kind==='keywords')return `<p class="apa-normal" data-section-key="${esc(x.key)}"${wizard.prompts?' data-template-prompt="true"':''}><em>${esc(text)}:</em> ${wizard.prompts?'['+esc(x.guide)+']':''}</p>`;return `<h${level} class="h${level}" data-section-key="${esc(x.key)}">${level>=4?'<span class="runin">'+esc(text.replace(/\.$/,'')+'.')+'</span> ':esc(text)}</h${level}><p class="${x.key==='referencias'?'reference':x.kind==='noindent'?'apa-noindent':'apa-normal'}"${wizard.prompts?' data-template-prompt="true"':''}>${wizard.prompts?'['+esc(x.guide||'Completa este apartado según tu encargo.')+']':'<br>'}</p>`}).join('');loadDoc({id:uid(),name:wizard.data.Title||'Documento académico',html:html||'<p class="apa-normal"><br></p>',refs:[],config:{type:wizard.type,institutionRules:'',modelId:m.id,modelRevision:CATALOG_DATA.revision,modelSourceIds:m.sources,modelChecked:m.checked,modelAck:wizard.ack,journal:wizard.journal,modelChecks:{}},cover:wizard.data,progress:[]});closeModal('wizardModal');saveState();toast('Documento creado. Escribe en la hoja y consulta la guía del apartado cuando la necesites.');if(wizard.cover)markProgress(0)}
